#!/usr/bin/env python3
"""Bouwt en/index.html en de/index.html uit de Nederlandse index.html.
Elke NL-tekst moet exact gevonden worden; anders stopt het script."""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
src = (ROOT / "index.html").read_text(encoding="utf-8")
# SEO/GEO-blok wordt per taal opnieuw gemaakt door tools/seo.py
src = re.sub(r"<!-- SEO:START.*?<!-- SEO:END -->\n?", "", src, flags=re.S)
src = re.sub(r'<script type="application/ld\+json">.*?</script>\n?', "", src, flags=re.S)

# Structurele vervangingen (paden, ankers, taalknoppen) per taal
def structural(lang):
    ids = {
        "en": {"over": "about", "seizoenen": "seasons", "wildschonau": "wildschoenau",
               "bereikbaarheid": "getting-there", "praktisch": "practical", "verblijf": "stay", "geschiedenis": "history", "lanerkoepfl": "lanerkoepfl", "activiteiten": "activities"},
        "de": {"over": "dorf", "seizoenen": "jahreszeiten", "wildschonau": "wildschoenau",
               "bereikbaarheid": "anreise", "praktisch": "praktisch", "verblijf": "unterkunft", "geschiedenis": "geschichte", "lanerkoepfl": "lanerkoepfl", "activiteiten": "aktivitaeten"},
    }[lang]
    pairs = []
    for nl, new in ids.items():
        pairs += [(f'id="{nl}"', f'id="{new}"'), (f'href="#{nl}"', f'href="#{new}"')]
    pairs += [
        ('href="assets/', 'href="../assets/'),
        ('src="assets/', 'src="../assets/'),
        ('<html lang="nl">', f'<html lang="{lang}">'),
        ('<link rel="canonical" href="https://niederau.nl/">', f'<link rel="canonical" href="https://niederau.nl/{lang}/">'),
        ('<meta property="og:url" content="https://niederau.nl/">', f'<meta property="og:url" content="https://niederau.nl/{lang}/">'),
        ('"url": "https://niederau.nl/",', f'"url": "https://niederau.nl/{lang}/",'),
        ('"inLanguage": "nl",', f'"inLanguage": "{lang}",'),
        ('<meta property="og:locale" content="nl_NL">', '<meta property="og:locale" content="%s">' % ("en_GB" if lang == "en" else "de_DE")),
        ('<a href="./" hreflang="nl" lang="nl" aria-current="true">NL</a>', '<a href="../" hreflang="nl" lang="nl">NL</a>'),
        ('<a href="en/" hreflang="en" lang="en">EN</a>',
         '<a href="./" hreflang="en" lang="en" aria-current="true">EN</a>' if lang == "en" else '<a href="../en/" hreflang="en" lang="en">EN</a>'),
        ('<a href="de/" hreflang="de" lang="de">DE</a>',
         '<a href="./" hreflang="de" lang="de" aria-current="true">DE</a>' if lang == "de" else '<a href="../de/" hreflang="de" lang="de">DE</a>'),
    ]
    return pairs

T = {}
T["en"] = [
    ("<title>Niederau, Wildschönau (Tirol): skiën, wandelen & tips</title>",
     "<title>Niederau, Wildschönau (Tyrol): skiing, hiking & tips</title>"),
    ('content="Niederau, zonnig bergdorp in de Wildschönau (Tirol): skiën in Ski Juwel, wandelen, geschiedenis, route en praktische tips – in zomer en winter."',
     'content="Niederau, sunny mountain village in the Wildschönau (Tyrol): skiing in Ski Juwel, hiking, history, getting there and practical tips – summer and winter."'),
    ('content="Niederau – het hart van de Wildschönau"', 'content="Niederau – the heart of the Wildschönau"'),
    ('content="Bergdorp op 828 meter in Tirol. Skiën, wandelen en genieten in de Wildschönau – met praktische tips."',
     'content="Mountain village at 828 metres in Tyrol. Skiing, hiking and enjoying life in the Wildschönau – with practical tips."'),
    ('"description": "Bergdorp in de Wildschönau, Tirol, Oostenrijk.",', '"description": "Mountain village in the Wildschönau valley, Tyrol, Austria.",'),
    ('"name": "Wildschönau, Tirol, Oostenrijk"', '"name": "Wildschönau, Tyrol, Austria"'),
    ('"touristType": ["Wintersport", "Wandelen", "Gezinnen"]', '"touristType": ["Winter sports", "Hiking", "Families"]'),
    ('<a class="skip" href="#main">Naar de inhoud</a>', '<a class="skip" href="#main">Skip to content</a>'),
    ('aria-label="Niederau.nl – naar boven"', 'aria-label="Niederau.nl – back to top"'),
    ("<small>Wildschönau · Tirol</small>", "<small>Wildschönau · Tyrol</small>"),
    ('aria-label="Hoofdmenu"', 'aria-label="Main menu"'),
    ('<a href="#about">Het dorp</a>', '<a href="#about">The village</a>'),
    ('<a href="#seasons">Zomer &amp; winter</a>', '<a href="#seasons">Summer &amp; winter</a>'),
    ('<a href="#getting-there">Route</a>', '<a href="#getting-there">Getting there</a>'),
    ('<a href="#practical">Praktisch</a>', '<a href="#practical">Practical</a>'),
    ('aria-label="Taal"', 'aria-label="Language"'),
    ('<p class="eyebrow">Wildschönau · Tirol · Oostenrijk</p>', '<p class="eyebrow">Wildschönau · Tyrol · Austria</p>'),
    ("Het zonnige bergdorp aan het begin van de Wildschönau. Een plek om te skiën, te wandelen en elk jaar weer thuis te komen.",
     "The sunny mountain village at the entrance to the Wildschönau valley. A place to ski, to hike and to come home to, year after year."),
    ("<li>828 m hoogte</li>", "<li>828 m altitude</li>"),
    ("<li>± 15 min. van Wörgl</li>", "<li>± 15 min from Wörgl</li>"),
    ("Ontdek zomer &amp; winter</a>", "Discover summer &amp; winter</a>"),
    ("Hoe kom je er?</a>", "How to get there</a>"),
    ('<p class="eyebrow">Het dorp</p>', '<p class="eyebrow">The village</p>'),
    ("Welkom in Niederau</h2>", "Welcome to Niederau</h2>"),
    ("<p>Niederau ligt in de <strong>Wildschönau</strong>, in <strong>Tirol</strong> (Oostenrijk). Het is het eerste dorp dat je bereikt als je vanuit het Inndal bij Wörgl de bergweg omhoog rijdt het dal in. Het ligt op zo’n 828 meter hoogte in een breed, groen hoogdal, omringd door bergweiden, bossen en toppen in de Kitzbüheler Alpen.</p>",
     "<p>Niederau lies in the <strong>Wildschönau</strong> valley in <strong>Tyrol</strong> (Austria). It is the first village you reach when you drive up the mountain road from Wörgl in the Inn valley. It lies at about 828 metres in a wide, green high valley, surrounded by alpine meadows, forests and the peaks of the Kitzbühel Alps.</p>"),
    ("<p>Samen met Oberau, Auffach en Thierbach vormt Niederau de gemeente <strong>Wildschönau</strong> in het district Kufstein. Het dorp is van oudsher geliefd bij Nederlandse en Britse gasten: compact, gemoedelijk, met skischolen, pensions en hotels op loopafstand van de lift.</p>",
     "<p>Together with Oberau, Auffach and Thierbach, Niederau forms the municipality of <strong>Wildschönau</strong> in the Kufstein district. The village has long been a favourite with Dutch and British guests: compact and friendly, with ski schools, guesthouses and hotels within walking distance of the lift.</p>"),
    ('aria-label="Niederau in cijfers"', 'aria-label="Niederau in numbers"'),
    ("<span>hoogte van het dorp</span>", "<span>altitude of the village</span>"),
    ("<strong>± 1.500 m</strong><span>Markbachjoch, bereikbaar met de gondel</span>", "<strong>± 1,500 m</strong><span>Markbachjoch, reached by gondola</span>"),
    ("<strong>4 dorpen</strong><span>samen de Wildschönau</span>", "<strong>4 villages</strong><span>together the Wildschönau</span>"),
    ("<span>pistes in Ski Juwel Alpbachtal Wildschönau</span>", "<span>of slopes in Ski Juwel Alpbachtal Wildschönau</span>"),
    ('<p class="eyebrow">Zomer &amp; winter</p>', '<p class="eyebrow">Summer &amp; winter</p>'),
    ("Twee seizoenen, één dorp</h2>", "Two seasons, one village</h2>"),
    ("<p>In de winter een overzichtelijk skidorp met een directe aansluiting op een groot skigebied, in de zomer een rustige uitvalsbasis voor wandelaars, fietsers en gezinnen.</p>",
     "<p>In winter a manageable ski village with direct access to a large ski area; in summer a peaceful base for hikers, cyclists and families.</p>"),
    ('aria-label="Kies seizoen"', 'aria-label="Choose season"'),
    ("☀ Zomer</button>", "☀ Summer</button>"),
    ("</span>Skiën vanuit het dorp</h3>", "</span>Skiing from the village</h3>"),
    ("<p>De Markbachjochbahn brengt je vanuit Niederau omhoog naar het Markbachjoch. Brede, zonnige pistes, ideaal voor beginners en gezinnen, met afdalingen terug tot in het dorp.</p>",
     "<p>The Markbachjochbahn gondola takes you from Niederau up to the Markbachjoch. Wide, sunny slopes, ideal for beginners and families, with runs all the way back down to the village.</p>"),
    ("<p>Met de skipas van Ski Juwel Alpbachtal Wildschönau ski je ook op de Schatzberg in Auffach en via de verbinding door naar het Alpbachtal. De skibus rijdt tussen de dorpen.</p>",
     "<p>With the Ski Juwel Alpbachtal Wildschönau lift pass you can also ski the Schatzberg in Auffach and continue over the link into the Alpbach valley. The ski bus runs between the villages.</p>"),
    ("</span>Skischool &amp; kinderen</h3>", "</span>Ski school &amp; children</h3>"),
    ("<p>Niederau heeft van oudsher sterke skischolen met lessen in het Nederlands, Engels en Duits, en oefenweides vlak bij het dorp. Een fijne plek om te leren skiën.</p>",
     "<p>Niederau has long had strong ski schools with lessons in Dutch, English and German, and nursery slopes close to the village. A great place to learn to ski.</p>"),
    ("</span>Langlaufen &amp; winterwandelen</h3>", "</span>Cross-country &amp; winter walks</h3>"),
    ("<p>Loipes door het dal en geruimde winterwandelpaden langs boerderijen en kapelletjes. Ook sneeuwschoenwandelen en rodelen zijn populair: het dal telt drie rodelbanen, die van het Lahnerköpfl ligt in Niederau zelf.</p>",
     "<p>Cross-country trails through the valley and cleared winter footpaths past farms and little chapels. Snowshoeing and tobogganing are popular too: the valley has three toboggan runs, and the Lahnerköpfl run is in Niederau itself.</p>"),
    ("<p>Gezellig zonder overdreven te zijn: na een dag op de latten schuif je aan in een berghut of in het dorp voor Glühwein, Kaiserschmarrn of een Tiroler Gröstl.</p>",
     "<p>Cosy without being over the top: after a day on the slopes, settle into a mountain hut or a village inn for Glühwein, Kaiserschmarrn or a Tyrolean Gröstl.</p>"),
    ("</span>Zonnig dorp</h3>", "</span>A sunny village</h3>"),
    ("<p>Niederau ligt open in het dal en krijgt veel zon – heerlijk op een terras in maart, wanneer de dagen langer worden en de sneeuw nog goed is.</p>",
     "<p>Niederau sits open in the valley and gets plenty of sun – wonderful on a terrace in March, when the days grow longer and the snow is still good.</p>"),
    ("</span>Wandelen</h3>", "</span>Hiking</h3>"),
    ("<p>Honderden kilometers gemarkeerde wandelpaden: van rustige dalwandelingen tot tochten over de bergkammen rond het dal. Met de gondel ben je in een paar minuten op hoogte.</p>",
     "<p>Hundreds of kilometres of waymarked trails: from gentle valley walks to hikes along the ridges around the valley. The gondola gets you up high in a few minutes.</p>"),
    ("<p>Een van de mooiste kloofwandelingen van Tirol: vanuit de Wildschönau langs de woeste Wildschönauer Ache naar beneden, naar Kundl in het Inndal.</p>",
     "<p>One of the finest gorge walks in Tyrol: from the Wildschönau down along the wild Wildschönauer Ache to Kundl in the Inn valley.</p>"),
    ("</span>(E-)mountainbiken</h3>", "</span>(E-)mountain biking</h3>"),
    ("<p>Bosweggen en bergweggetjes naar de almen; met een e-bike zijn ook de hoger gelegen hutten goed bereikbaar.</p>",
     "<p>Forest tracks and mountain lanes up to the alpine pastures; with an e-bike even the higher huts are within easy reach.</p>"),
    ("</span>Almen &amp; berghutten</h3>", "</span>Alpine pastures &amp; huts</h3>"),
    ("<p>In de zomer zijn veel almen open (“bewirtschaftet”): kaas, karnemelk, speck en Kaspressknödel met uitzicht op de Hohe Tauern en het Kaisergebergte.</p>",
     "<p>In summer many alpine huts are open: cheese, buttermilk, speck and Kaspressknödel with views of the Hohe Tauern and the Kaiser mountains.</p>"),
    ("</span>Met kinderen</h3>", "</span>With children</h3>"),
    ("<p>Speeltuinen, beekjes om te dammen, boerderijdieren en korte wandelingen met een hut als beloning. De Wildschönau is ingericht op gezinnen. Aan de rand van Niederau ligt een openluchtzwembad met drie bassins en een grote glijbaan.</p>",
     "<p>Playgrounds, streams to dam, farm animals and short walks with a hut as the reward. The Wildschönau is made for families. On the edge of Niederau there is an open-air pool with three basins and a big water slide.</p>"),
    ("</span>Traditie</h3>", "</span>Tradition</h3>"),
    ("<p>Blaasmuziek op het dorpsplein, kerkelijke feestdagen en de Almabtrieb in het najaar, wanneer het vee versierd terugkeert uit de bergen.</p>",
     "<p>Brass bands on the village square, church holidays and the Almabtrieb in autumn, when the decorated cattle return from the mountains.</p>"),
    ('<p class="eyebrow">De Wildschönau</p>', '<p class="eyebrow">The Wildschönau</p>'),
    ("Eén dal, vier dorpen</h2>", "One valley, four villages</h2>"),
    ("<p>De Wildschönau is een zijdal van het Inndal, hoog boven Wörgl. Elk dorp heeft zijn eigen karakter.</p>",
     "<p>The Wildschönau is a side valley of the Inn valley, high above Wörgl. Each village has its own character.</p>"),
    ("<p>Het eerste en meest toeristische dorp, met de gondel naar het Markbachjoch en het grootste aanbod aan accommodatie.</p>",
     "<p>The first and most visited village, with the gondola to the Markbachjoch and the widest choice of accommodation.</p>"),
    ("<p>Het bestuurlijke hart van het dal, met de grote parochiekerk en een brede, zonnige vlakte.</p>",
     "<p>The administrative heart of the valley, with the large parish church and a wide, sunny plateau.</p>"),
    ("<p>Achter in het dal, aan de voet van de Schatzberg en de verbinding met het Alpbachtal.</p>",
     "<p>At the far end of the valley, at the foot of the Schatzberg and the link to the Alpbach valley.</p>"),
    ("<span class=\"alt-badge\">± 1.150 m</span>", "<span class=\"alt-badge\">± 1,150 m</span>"),
    ("<p>Het kleinste en hoogst gelegen dorp, rustig en met weids uitzicht over het Inndal.</p>",
     "<p>The smallest and highest village, quiet and with sweeping views over the Inn valley.</p>"),
    ("<h3>Krautinger – de schnaps van het dal</h3>", "<h3>Krautinger – the valley’s own schnapps</h3>"),
    ("<p>De Wildschönau staat bekend om <em>Krautinger</em>, een stevige brandewijn gestookt van witte knollen (stoppelknollen). Volgens de overlevering kregen de boeren van het dal het recht om hem te stoken al in de tijd van keizerin Maria Theresia. Alleen een beperkt aantal boerderijen mag hem nog maken – proeven doe je op de boerderij zelf.</p>",
     "<p>The Wildschönau is known for <em>Krautinger</em>, a strong spirit distilled from white turnips. According to tradition, the valley’s farmers were granted the right to distil it as far back as Empress Maria Theresa. Only a limited number of farms may still make it – you taste it at the farm itself.</p>"),
    ("<h3>Tiroolse keuken</h3>", "<h3>Tyrolean cooking</h3>"),
    ("– gescheurde pannenkoek met poedersuiker en appelmoes</li>", "– shredded pancake with icing sugar and apple sauce</li>"),
    ("– kaasknoedels, in soep of met salade</li>", "– cheese dumplings, in soup or with salad</li>"),
    ("– gebakken aardappel, spek en ui met een ei</li>", "– fried potatoes, bacon and onion topped with an egg</li>"),
    ("<li><strong>Speckknödel</strong> en verse <strong>almkaas</strong></li>", "<li><strong>Speckknödel</strong> and fresh <strong>alpine cheese</strong></li>"),
    ('<p class="eyebrow">Bereikbaarheid</p>', '<p class="eyebrow">Getting there</p>'),
    ("Zo kom je in Niederau</h2>", "How to reach Niederau</h2>"),
    ("<h3>Met de auto</h3>", "<h3>By car</h3>"),
    ("<li>Via Duitsland (München of Rosenheim) naar de grensovergang Kiefersfelden/Kufstein.</li>",
     "<li>Through Germany (Munich or Rosenheim) to the Kiefersfelden/Kufstein border crossing.</li>"),
    ("<li>In Oostenrijk de A12 Inntal Autobahn richting Innsbruck volgen; neem de afslag <strong>Wörgl-Ost</strong>.</li>",
     "<li>In Austria follow the A12 Inntal motorway towards Innsbruck; take the <strong>Wörgl-Ost</strong> exit.</li>"),
    ("<li>Volg in Wörgl de borden <strong>Wildschönau</strong>. De bergweg klimt in zo’n 15 minuten naar Niederau.</li>",
     "<li>In Wörgl follow the signs for <strong>Wildschönau</strong>. The mountain road climbs to Niederau in about 15 minutes.</li>"),
    ("<p class=\"note\">Let op: op de Oostenrijkse snelweg heb je een <strong>vignet</strong> nodig (digitaal of als sticker). Vanuit Midden-Nederland reken je op circa 9 à 10 uur rijden.</p>",
     "<p class=\"note\">Note: Austrian motorways require a <strong>vignette</strong> (digital or sticker). From the central Netherlands, allow around 9 to 10 hours’ driving.</p>"),
    ("<h3>Met de trein</h3>", "<h3>By train</h3>"),
    ("<p>Treinstation <strong>Wörgl Hbf</strong> ligt aan de hoofdlijn München – Innsbruck en heeft goede verbindingen, ook met nachttreinen. Vanaf Wörgl rijdt een streekbus de Wildschönau in.</p>",
     "<p><strong>Wörgl Hbf</strong> station is on the main Munich – Innsbruck line and is well connected, including by night trains. From Wörgl a regional bus runs up into the Wildschönau.</p>"),
    ("<h3>Met het vliegtuig</h3>", "<h3>By air</h3>"),
    ("<p>Dichtstbijzijnde luchthavens: <strong>Innsbruck</strong> (± 1 uur), <strong>Salzburg</strong> (± 1,5 uur) en <strong>München</strong> (± 2 uur).</p>",
     "<p>Nearest airports: <strong>Innsbruck</strong> (± 1 hour), <strong>Salzburg</strong> (± 1.5 hours) and <strong>Munich</strong> (± 2 hours).</p>"),
    ("Schematische kaart van de Wildschönau tussen Kundl en Wörgl</title>", "Schematic map of the Wildschönau between Kundl and Wörgl</title>"),
    (">Schematisch, niet op schaal</text>", ">Schematic, not to scale</text>"),
    ('<p class="eyebrow">Praktisch</p>', '<p class="eyebrow">Practical</p>'),
    ("Goed om te weten</h2>", "Good to know</h2>"),
    ("<summary>Wanneer is de beste tijd om te gaan?</summary>", "<summary>When is the best time to go?</summary>"),
    ("<p>Voor wintersport is half januari tot half maart het meest sneeuwzeker; maart is extra zonnig. In de zomer zijn juni en september rustiger dan de Duitse en Nederlandse schoolvakanties, met prima wandelweer.</p>",
     "<p>For skiing, mid-January to mid-March is the most snow-sure period; March is especially sunny. In summer, June and September are quieter than the school holidays, with fine hiking weather.</p>"),
    ("<summary>Heb ik een vignet nodig?</summary>", "<summary>Do I need a vignette?</summary>"),
    ("<p>Ja, voor de Oostenrijkse snelwegen (zoals de A12 naar Wörgl). Je koopt het online bij ASFINAG of bij tankstations vlak voor de grens. Een digitaal vignet moet je bij online aankoop enkele dagen van tevoren kopen.</p>",
     "<p>Yes, for Austrian motorways (such as the A12 to Wörgl). You can buy it online from ASFINAG or at petrol stations just before the border. If you buy a digital vignette online, do so a few days in advance.</p>"),
    ("<summary>Is Niederau geschikt voor beginners en gezinnen?</summary>", "<summary>Is Niederau suitable for beginners and families?</summary>"),
    ("<p>Zeker. De brede pistes rond het Markbachjoch, de oefenweides bij het dorp en de skischolen maken Niederau van oudsher populair bij families en beginnende skiërs.</p>",
     "<p>Definitely. The wide slopes around the Markbachjoch, the nursery slopes by the village and the ski schools have long made Niederau popular with families and beginners.</p>"),
    ("<summary>Spreekt men er Nederlands of Engels?</summary>", "<summary>Do people speak English?</summary>"),
    ("<p>De voertaal is Duits (met een stevig Tirools dialect), maar in hotels, skischolen en restaurants red je je goed met Engels, en vaak ook met Nederlands.</p>",
     "<p>The local language is German (with a strong Tyrolean dialect), but in hotels, ski schools and restaurants you will get by fine in English, and often in Dutch too.</p>"),
    ("<summary>Welke noodnummers moet ik kennen?</summary>", "<summary>Which emergency numbers should I know?</summary>"),
    ("<p>Algemeen alarmnummer <strong>112</strong>. Bergredding in Oostenrijk: <strong>140</strong>. Check vóór een toer in de winter altijd het lawinebulletin.</p>",
     "<p>General emergency number <strong>112</strong>. Mountain rescue in Austria: <strong>140</strong>. In winter, always check the avalanche bulletin before a tour.</p>"),
    ("<summary>Waar vind ik actuele informatie over liften, sneeuw en evenementen?</summary>", "<summary>Where can I find current information on lifts, snow and events?</summary>"),
    ("<p>Bij de officiële toeristische organisatie van de Wildschönau en bij Ski Juwel. Zie de links hiernaast.</p>",
     "<p>From the official Wildschönau tourist board and from Ski Juwel. See the links alongside.</p>"),
    ("<h3>Nuttige links</h3>", "<h3>Useful links</h3>"),
    ("<small>Officiële info, accommodatie, evenementen</small>", "<small>Official info, accommodation, events</small>"),
    ("<small>Liften, pistes, skipassen</small>", "<small>Lifts, slopes, lift passes</small>"),
    (">Lawinebulletin Tirol<small>", ">Tyrol avalanche bulletin<small>"),
    ("<small>Vignet en verkeersinfo</small>", "<small>Vignette and traffic info</small>"),
    ("<small>Treinen naar Wörgl</small>", "<small>Trains to Wörgl</small>"),
    ("<small>Bussen in Tirol</small>", "<small>Buses in Tyrol</small>"),
    ("Niederau.nl is een onafhankelijke site en niet verbonden aan de toeristische organisatie of de liftmaatschappij. Controleer actuele tijden en prijzen altijd bij de officiële bronnen.</p>",
     "Niederau.nl is an independent site and is not affiliated with the tourist board or the lift company. Always check current times and prices with the official sources.</p>"),
    ("<p>Onafhankelijke gids over Niederau in de Wildschönau, Tirol: het dorp, zomer en winter, route en praktische tips.</p>",
     "<p>Independent guide to Niederau in the Wildschönau, Tyrol: the village, summer and winter, getting there and practical tips.</p>"),
    ("<h4>Op deze site</h4>", "<h4>On this site</h4>"),
    ("<h4>Meer</h4>", "<h4>More</h4>"),
    ('<a href="#practical">Praktische info</a>', '<a href="#practical">Practical info</a>'),
    ("Niederau.nl · Onafhankelijke site, niet verbonden aan officiële instanties.</p>", "Niederau.nl · Independent site, not affiliated with any official body.</p>"),
]

T["de"] = [
    ("<title>Niederau, Wildschönau (Tirol): skiën, wandelen & tips</title>",
     "<title>Niederau, Wildschönau (Tirol): Skifahren, Wandern & Tipps</title>"),
    ('content="Niederau, zonnig bergdorp in de Wildschönau (Tirol): skiën in Ski Juwel, wandelen, geschiedenis, route en praktische tips – in zomer en winter."',
     'content="Niederau, sonniges Bergdorf in der Wildschönau (Tirol): Skifahren im Ski Juwel, Wandern, Geschichte, Anreise und Tipps – im Sommer und Winter."'),
    ('content="Niederau – het hart van de Wildschönau"', 'content="Niederau – das Herz der Wildschönau"'),
    ('content="Bergdorp op 828 meter in Tirol. Skiën, wandelen en genieten in de Wildschönau – met praktische tips."',
     'content="Bergdorf auf 828 Metern in Tirol. Skifahren, Wandern und Genießen in der Wildschönau – mit praktischen Tipps."'),
    ('"description": "Bergdorp in de Wildschönau, Tirol, Oostenrijk.",', '"description": "Bergdorf in der Wildschönau, Tirol, Österreich.",'),
    ('"name": "Wildschönau, Tirol, Oostenrijk"', '"name": "Wildschönau, Tirol, Österreich"'),
    ('"touristType": ["Wintersport", "Wandelen", "Gezinnen"]', '"touristType": ["Wintersport", "Wandern", "Familien"]'),
    ('<a class="skip" href="#main">Naar de inhoud</a>', '<a class="skip" href="#main">Zum Inhalt</a>'),
    ('aria-label="Niederau.nl – naar boven"', 'aria-label="Niederau.nl – nach oben"'),
    ('aria-label="Hoofdmenu"', 'aria-label="Hauptmenü"'),
    ('<button class="menu-btn" aria-expanded="false" aria-controls="nav">Menu</button>', '<button class="menu-btn" aria-expanded="false" aria-controls="nav">Menü</button>'),
    ('<a href="#dorf">Het dorp</a>', '<a href="#dorf">Das Dorf</a>'),
    ('<a href="#jahreszeiten">Zomer &amp; winter</a>', '<a href="#jahreszeiten">Sommer &amp; Winter</a>'),
    ('<a href="#anreise">Route</a>', '<a href="#anreise">Anreise</a>'),
    ('<a href="#praktisch">Praktisch</a>', '<a href="#praktisch">Praktisches</a>'),
    ('aria-label="Taal"', 'aria-label="Sprache"'),
    ('<p class="eyebrow">Wildschönau · Tirol · Oostenrijk</p>', '<p class="eyebrow">Wildschönau · Tirol · Österreich</p>'),
    ("Het zonnige bergdorp aan het begin van de Wildschönau. Een plek om te skiën, te wandelen en elk jaar weer thuis te komen.",
     "Das sonnige Bergdorf am Eingang der Wildschönau. Ein Ort zum Skifahren, zum Wandern und um jedes Jahr wieder nach Hause zu kommen."),
    ("<li>828 m hoogte</li>", "<li>828 m Seehöhe</li>"),
    ("<li>± 15 min. van Wörgl</li>", "<li>± 15 Min. von Wörgl</li>"),
    ("Ontdek zomer &amp; winter</a>", "Sommer &amp; Winter entdecken</a>"),
    ("Hoe kom je er?</a>", "Wie kommt man hin?</a>"),
    ('<p class="eyebrow">Het dorp</p>', '<p class="eyebrow">Das Dorf</p>'),
    ("Welkom in Niederau</h2>", "Willkommen in Niederau</h2>"),
    ("<p>Niederau ligt in de <strong>Wildschönau</strong>, in <strong>Tirol</strong> (Oostenrijk). Het is het eerste dorp dat je bereikt als je vanuit het Inndal bij Wörgl de bergweg omhoog rijdt het dal in. Het ligt op zo’n 828 meter hoogte in een breed, groen hoogdal, omringd door bergweiden, bossen en toppen in de Kitzbüheler Alpen.</p>",
     "<p>Niederau liegt in der <strong>Wildschönau</strong> in <strong>Tirol</strong> (Österreich). Es ist das erste Dorf, das man erreicht, wenn man von Wörgl im Inntal die Bergstraße hinauf ins Tal fährt. Es liegt auf rund 828 Metern in einem weiten, grünen Hochtal, umgeben von Almwiesen, Wäldern und den Gipfeln der Kitzbüheler Alpen.</p>"),
    ("<p>Samen met Oberau, Auffach en Thierbach vormt Niederau de gemeente <strong>Wildschönau</strong> in het district Kufstein. Het dorp is van oudsher geliefd bij Nederlandse en Britse gasten: compact, gemoedelijk, met skischolen, pensions en hotels op loopafstand van de lift.</p>",
     "<p>Gemeinsam mit Oberau, Auffach und Thierbach bildet Niederau die Gemeinde <strong>Wildschönau</strong> im Bezirk Kufstein. Das Dorf ist seit jeher bei niederländischen und britischen Gästen beliebt: kompakt, gemütlich, mit Skischulen, Pensionen und Hotels in Gehweite zum Lift.</p>"),
    ('aria-label="Niederau in cijfers"', 'aria-label="Niederau in Zahlen"'),
    ("<span>hoogte van het dorp</span>", "<span>Seehöhe des Dorfes</span>"),
    ("<span>Markbachjoch, bereikbaar met de gondel</span>", "<span>Markbachjoch, mit der Gondel erreichbar</span>"),
    ("<strong>4 dorpen</strong><span>samen de Wildschönau</span>", "<strong>4 Dörfer</strong><span>bilden die Wildschönau</span>"),
    ("<span>pistes in Ski Juwel Alpbachtal Wildschönau</span>", "<span>Pisten im Ski Juwel Alpbachtal Wildschönau</span>"),
    ('<p class="eyebrow">Zomer &amp; winter</p>', '<p class="eyebrow">Sommer &amp; Winter</p>'),
    ("Twee seizoenen, één dorp</h2>", "Zwei Jahreszeiten, ein Dorf</h2>"),
    ("<p>In de winter een overzichtelijk skidorp met een directe aansluiting op een groot skigebied, in de zomer een rustige uitvalsbasis voor wandelaars, fietsers en gezinnen.</p>",
     "<p>Im Winter ein überschaubares Skidorf mit direktem Zugang zu einem großen Skigebiet, im Sommer ein ruhiger Ausgangspunkt für Wanderer, Radfahrer und Familien.</p>"),
    ('aria-label="Kies seizoen"', 'aria-label="Jahreszeit wählen"'),
    ("☀ Zomer</button>", "☀ Sommer</button>"),
    ("</span>Skiën vanuit het dorp</h3>", "</span>Skifahren direkt vom Dorf</h3>"),
    ("<p>De Markbachjochbahn brengt je vanuit Niederau omhoog naar het Markbachjoch. Brede, zonnige pistes, ideaal voor beginners en gezinnen, met afdalingen terug tot in het dorp.</p>",
     "<p>Die Markbachjochbahn bringt Sie von Niederau hinauf zum Markbachjoch. Breite, sonnige Pisten, ideal für Anfänger und Familien, mit Abfahrten bis ins Dorf.</p>"),
    ("<p>Met de skipas van Ski Juwel Alpbachtal Wildschönau ski je ook op de Schatzberg in Auffach en via de verbinding door naar het Alpbachtal. De skibus rijdt tussen de dorpen.</p>",
     "<p>Mit dem Skipass des Ski Juwel Alpbachtal Wildschönau fahren Sie auch am Schatzberg in Auffach und über die Verbindung weiter ins Alpbachtal. Der Skibus pendelt zwischen den Dörfern.</p>"),
    ("</span>Skischool &amp; kinderen</h3>", "</span>Skischule &amp; Kinder</h3>"),
    ("<p>Niederau heeft van oudsher sterke skischolen met lessen in het Nederlands, Engels en Duits, en oefenweides vlak bij het dorp. Een fijne plek om te leren skiën.</p>",
     "<p>Niederau hat seit jeher starke Skischulen mit Unterricht auf Niederländisch, Englisch und Deutsch sowie Übungswiesen direkt beim Dorf. Ein schöner Ort, um Skifahren zu lernen.</p>"),
    ("</span>Langlaufen &amp; winterwandelen</h3>", "</span>Langlaufen &amp; Winterwandern</h3>"),
    ("<p>Loipes door het dal en geruimde winterwandelpaden langs boerderijen en kapelletjes. Ook sneeuwschoenwandelen en rodelen zijn populair: het dal telt drie rodelbanen, die van het Lahnerköpfl ligt in Niederau zelf.</p>",
     "<p>Loipen durchs Tal und geräumte Winterwanderwege vorbei an Bauernhöfen und Kapellen. Auch Schneeschuhwandern und Rodeln sind beliebt: Das Tal hat drei Rodelbahnen, die am Lahnerköpfl liegt in Niederau selbst.</p>"),
    ("<p>Gezellig zonder overdreven te zijn: na een dag op de latten schuif je aan in een berghut of in het dorp voor Glühwein, Kaiserschmarrn of een Tiroler Gröstl.</p>",
     "<p>Gemütlich, ohne übertrieben zu sein: Nach einem Skitag kehrt man in einer Hütte oder im Dorf ein – auf Glühwein, Kaiserschmarrn oder ein Tiroler Gröstl.</p>"),
    ("</span>Zonnig dorp</h3>", "</span>Sonniges Dorf</h3>"),
    ("<p>Niederau ligt open in het dal en krijgt veel zon – heerlijk op een terras in maart, wanneer de dagen langer worden en de sneeuw nog goed is.</p>",
     "<p>Niederau liegt offen im Tal und bekommt viel Sonne – herrlich auf einer Terrasse im März, wenn die Tage länger werden und der Schnee noch gut ist.</p>"),
    ("</span>Wandelen</h3>", "</span>Wandern</h3>"),
    ("<p>Honderden kilometers gemarkeerde wandelpaden: van rustige dalwandelingen tot tochten over de bergkammen rond het dal. Met de gondel ben je in een paar minuten op hoogte.</p>",
     "<p>Hunderte Kilometer markierte Wanderwege: von gemütlichen Talwanderungen bis zu Touren über die Bergkämme rund ums Tal. Mit der Gondel ist man in wenigen Minuten oben.</p>"),
    ("<p>Een van de mooiste kloofwandelingen van Tirol: vanuit de Wildschönau langs de woeste Wildschönauer Ache naar beneden, naar Kundl in het Inndal.</p>",
     "<p>Eine der schönsten Klammwanderungen Tirols: von der Wildschönau entlang der wilden Wildschönauer Ache hinunter nach Kundl im Inntal.</p>"),
    ("</span>(E-)mountainbiken</h3>", "</span>(E-)Mountainbiken</h3>"),
    ("<p>Bosweggen en bergweggetjes naar de almen; met een e-bike zijn ook de hoger gelegen hutten goed bereikbaar.</p>",
     "<p>Forstwege und Bergsträßchen hinauf zu den Almen; mit dem E-Bike sind auch die höher gelegenen Hütten gut erreichbar.</p>"),
    ("</span>Almen &amp; berghutten</h3>", "</span>Almen &amp; Hütten</h3>"),
    ("<p>In de zomer zijn veel almen open (“bewirtschaftet”): kaas, karnemelk, speck en Kaspressknödel met uitzicht op de Hohe Tauern en het Kaisergebergte.</p>",
     "<p>Im Sommer sind viele Almen bewirtschaftet: Käse, Buttermilch, Speck und Kaspressknödel mit Blick auf die Hohen Tauern und das Kaisergebirge.</p>"),
    ("</span>Met kinderen</h3>", "</span>Mit Kindern</h3>"),
    ("<p>Speeltuinen, beekjes om te dammen, boerderijdieren en korte wandelingen met een hut als beloning. De Wildschönau is ingericht op gezinnen. Aan de rand van Niederau ligt een openluchtzwembad met drie bassins en een grote glijbaan.</p>",
     "<p>Spielplätze, Bäche zum Stauen, Bauernhoftiere und kurze Wanderungen mit einer Hütte als Belohnung. Die Wildschönau ist auf Familien eingestellt. Am Ortsrand von Niederau liegt ein Freibad mit drei Becken und einer großen Rutsche.</p>"),
    ("</span>Traditie</h3>", "</span>Tradition</h3>"),
    ("<p>Blaasmuziek op het dorpsplein, kerkelijke feestdagen en de Almabtrieb in het najaar, wanneer het vee versierd terugkeert uit de bergen.</p>",
     "<p>Blasmusik am Dorfplatz, kirchliche Feiertage und der Almabtrieb im Herbst, wenn das geschmückte Vieh von den Bergen zurückkehrt.</p>"),
    ('<p class="eyebrow">De Wildschönau</p>', '<p class="eyebrow">Die Wildschönau</p>'),
    ("Eén dal, vier dorpen</h2>", "Ein Tal, vier Dörfer</h2>"),
    ("<p>De Wildschönau is een zijdal van het Inndal, hoog boven Wörgl. Elk dorp heeft zijn eigen karakter.</p>",
     "<p>Die Wildschönau ist ein Seitental des Inntals, hoch über Wörgl. Jedes Dorf hat seinen eigenen Charakter.</p>"),
    ("<p>Het eerste en meest toeristische dorp, met de gondel naar het Markbachjoch en het grootste aanbod aan accommodatie.</p>",
     "<p>Das erste und touristischste Dorf, mit der Gondel zum Markbachjoch und dem größten Angebot an Unterkünften.</p>"),
    ("<p>Het bestuurlijke hart van het dal, met de grote parochiekerk en een brede, zonnige vlakte.</p>",
     "<p>Das Verwaltungszentrum des Tals, mit der großen Pfarrkirche und einem weiten, sonnigen Plateau.</p>"),
    ("<p>Achter in het dal, aan de voet van de Schatzberg en de verbinding met het Alpbachtal.</p>",
     "<p>Hinten im Tal, am Fuß des Schatzbergs und der Verbindung ins Alpbachtal.</p>"),
    ("<p>Het kleinste en hoogst gelegen dorp, rustig en met weids uitzicht over het Inndal.</p>",
     "<p>Das kleinste und höchstgelegene Dorf, ruhig und mit weitem Blick über das Inntal.</p>"),
    ("<h3>Krautinger – de schnaps van het dal</h3>", "<h3>Krautinger – der Schnaps des Tals</h3>"),
    ("<p>De Wildschönau staat bekend om <em>Krautinger</em>, een stevige brandewijn gestookt van witte knollen (stoppelknollen). Volgens de overlevering kregen de boeren van het dal het recht om hem te stoken al in de tijd van keizerin Maria Theresia. Alleen een beperkt aantal boerderijen mag hem nog maken – proeven doe je op de boerderij zelf.</p>",
     "<p>Die Wildschönau ist bekannt für den <em>Krautinger</em>, einen kräftigen Schnaps aus weißen Rüben (Stoppelrüben). Der Überlieferung nach erhielten die Bauern des Tals das Brennrecht schon zur Zeit Kaiserin Maria Theresias. Nur noch eine begrenzte Zahl von Höfen darf ihn brennen – verkostet wird direkt am Hof.</p>"),
    ("<h3>Tiroolse keuken</h3>", "<h3>Tiroler Küche</h3>"),
    ("– gescheurde pannenkoek met poedersuiker en appelmoes</li>", "– zerrissener Pfannkuchen mit Staubzucker und Apfelmus</li>"),
    ("– kaasknoedels, in soep of met salade</li>", "– Käseknödel, in der Suppe oder mit Salat</li>"),
    ("– gebakken aardappel, spek en ui met een ei</li>", "– Bratkartoffeln mit Speck und Zwiebeln, mit Spiegelei</li>"),
    ("<li><strong>Speckknödel</strong> en verse <strong>almkaas</strong></li>", "<li><strong>Speckknödel</strong> und frischer <strong>Almkäse</strong></li>"),
    ('<p class="eyebrow">Bereikbaarheid</p>', '<p class="eyebrow">Anreise</p>'),
    ("Zo kom je in Niederau</h2>", "So kommen Sie nach Niederau</h2>"),
    ("<h3>Met de auto</h3>", "<h3>Mit dem Auto</h3>"),
    ("<li>Via Duitsland (München of Rosenheim) naar de grensovergang Kiefersfelden/Kufstein.</li>",
     "<li>Über München oder Rosenheim zum Grenzübergang Kiefersfelden/Kufstein.</li>"),
    ("<li>In Oostenrijk de A12 Inntal Autobahn richting Innsbruck volgen; neem de afslag <strong>Wörgl-Ost</strong>.</li>",
     "<li>In Österreich der A12 Inntalautobahn Richtung Innsbruck folgen; Ausfahrt <strong>Wörgl-Ost</strong>.</li>"),
    ("<li>Volg in Wörgl de borden <strong>Wildschönau</strong>. De bergweg klimt in zo’n 15 minuten naar Niederau.</li>",
     "<li>In Wörgl der Beschilderung <strong>Wildschönau</strong> folgen. Die Bergstraße führt in rund 15 Minuten nach Niederau.</li>"),
    ("<p class=\"note\">Let op: op de Oostenrijkse snelweg heb je een <strong>vignet</strong> nodig (digitaal of als sticker). Vanuit Midden-Nederland reken je op circa 9 à 10 uur rijden.</p>",
     "<p class=\"note\">Hinweis: Auf österreichischen Autobahnen brauchen Sie eine <strong>Vignette</strong> (digital oder als Klebevignette). Von München aus sind es rund 1,5 Stunden Fahrt.</p>"),
    ("<h3>Met de trein</h3>", "<h3>Mit der Bahn</h3>"),
    ("<p>Treinstation <strong>Wörgl Hbf</strong> ligt aan de hoofdlijn München – Innsbruck en heeft goede verbindingen, ook met nachttreinen. Vanaf Wörgl rijdt een streekbus de Wildschönau in.</p>",
     "<p>Der Bahnhof <strong>Wörgl Hbf</strong> liegt an der Hauptstrecke München – Innsbruck und ist gut angebunden, auch mit Nachtzügen. Ab Wörgl fährt ein Regionalbus in die Wildschönau.</p>"),
    ("<h3>Met het vliegtuig</h3>", "<h3>Mit dem Flugzeug</h3>"),
    ("<p>Dichtstbijzijnde luchthavens: <strong>Innsbruck</strong> (± 1 uur), <strong>Salzburg</strong> (± 1,5 uur) en <strong>München</strong> (± 2 uur).</p>",
     "<p>Nächstgelegene Flughäfen: <strong>Innsbruck</strong> (± 1 Std.), <strong>Salzburg</strong> (± 1,5 Std.) und <strong>München</strong> (± 2 Std.).</p>"),
    ("Schematische kaart van de Wildschönau tussen Kundl en Wörgl</title>", "Schematische Karte der Wildschönau zwischen Kundl und Wörgl</title>"),
    (">Schematisch, niet op schaal</text>", ">Schematisch, nicht maßstabsgetreu</text>"),
    ('<p class="eyebrow">Praktisch</p>', '<p class="eyebrow">Praktisches</p>'),
    ("Goed om te weten</h2>", "Gut zu wissen</h2>"),
    ("<summary>Wanneer is de beste tijd om te gaan?</summary>", "<summary>Wann ist die beste Reisezeit?</summary>"),
    ("<p>Voor wintersport is half januari tot half maart het meest sneeuwzeker; maart is extra zonnig. In de zomer zijn juni en september rustiger dan de Duitse en Nederlandse schoolvakanties, met prima wandelweer.</p>",
     "<p>Zum Skifahren ist Mitte Jänner bis Mitte März am schneesichersten; der März ist besonders sonnig. Im Sommer sind Juni und September ruhiger als die Schulferien – bei bestem Wanderwetter.</p>"),
    ("<summary>Heb ik een vignet nodig?</summary>", "<summary>Brauche ich eine Vignette?</summary>"),
    ("<p>Ja, voor de Oostenrijkse snelwegen (zoals de A12 naar Wörgl). Je koopt het online bij ASFINAG of bij tankstations vlak voor de grens. Een digitaal vignet moet je bij online aankoop enkele dagen van tevoren kopen.</p>",
     "<p>Ja, für österreichische Autobahnen (wie die A12 nach Wörgl). Erhältlich online bei der ASFINAG oder an Tankstellen vor der Grenze. Eine online gekaufte digitale Vignette sollten Sie einige Tage im Voraus erwerben.</p>"),
    ("<summary>Is Niederau geschikt voor beginners en gezinnen?</summary>", "<summary>Ist Niederau für Anfänger und Familien geeignet?</summary>"),
    ("<p>Zeker. De brede pistes rond het Markbachjoch, de oefenweides bij het dorp en de skischolen maken Niederau van oudsher populair bij families en beginnende skiërs.</p>",
     "<p>Auf jeden Fall. Die breiten Pisten am Markbachjoch, die Übungswiesen beim Dorf und die Skischulen machen Niederau seit jeher beliebt bei Familien und Anfängern.</p>"),
    ("<summary>Spreekt men er Nederlands of Engels?</summary>", "<summary>Spricht man dort auch Englisch oder Niederländisch?</summary>"),
    ("<p>De voertaal is Duits (met een stevig Tirools dialect), maar in hotels, skischolen en restaurants red je je goed met Engels, en vaak ook met Nederlands.</p>",
     "<p>Umgangssprache ist Deutsch (mit kräftigem Tiroler Dialekt), aber in Hotels, Skischulen und Restaurants kommt man auch mit Englisch und oft mit Niederländisch gut zurecht.</p>"),
    ("<summary>Welke noodnummers moet ik kennen?</summary>", "<summary>Welche Notrufnummern sollte ich kennen?</summary>"),
    ("<p>Algemeen alarmnummer <strong>112</strong>. Bergredding in Oostenrijk: <strong>140</strong>. Check vóór een toer in de winter altijd het lawinebulletin.</p>",
     "<p>Euronotruf <strong>112</strong>. Bergrettung in Österreich: <strong>140</strong>. Prüfen Sie im Winter vor jeder Tour den Lawinenlagebericht.</p>"),
    ("<summary>Waar vind ik actuele informatie over liften, sneeuw en evenementen?</summary>", "<summary>Wo finde ich aktuelle Infos zu Liften, Schnee und Veranstaltungen?</summary>"),
    ("<p>Bij de officiële toeristische organisatie van de Wildschönau en bij Ski Juwel. Zie de links hiernaast.</p>",
     "<p>Beim offiziellen Tourismusverband Wildschönau und beim Ski Juwel. Siehe Links nebenan.</p>"),
    ("<h3>Nuttige links</h3>", "<h3>Nützliche Links</h3>"),
    ("<small>Officiële info, accommodatie, evenementen</small>", "<small>Offizielle Infos, Unterkünfte, Veranstaltungen</small>"),
    ("<small>Liften, pistes, skipassen</small>", "<small>Lifte, Pisten, Skipässe</small>"),
    (">Lawinebulletin Tirol<small>", ">Lawinenlagebericht Tirol<small>"),
    ("<small>Vignet en verkeersinfo</small>", "<small>Vignette und Verkehrsinfo</small>"),
    ("<small>Treinen naar Wörgl</small>", "<small>Züge nach Wörgl</small>"),
    ("<small>Bussen in Tirol</small>", "<small>Busse in Tirol</small>"),
    ("Niederau.nl is een onafhankelijke site en niet verbonden aan de toeristische organisatie of de liftmaatschappij. Controleer actuele tijden en prijzen altijd bij de officiële bronnen.</p>",
     "Niederau.nl ist eine unabhängige Seite und nicht mit dem Tourismusverband oder den Bergbahnen verbunden. Aktuelle Zeiten und Preise bitte immer bei den offiziellen Quellen prüfen.</p>"),
    ("<p>Onafhankelijke gids over Niederau in de Wildschönau, Tirol: het dorp, zomer en winter, route en praktische tips.</p>",
     "<p>Unabhängiger Führer über Niederau in der Wildschönau, Tirol: das Dorf, Sommer und Winter, Anreise und praktische Tipps.</p>"),
    ("<h4>Op deze site</h4>", "<h4>Auf dieser Seite</h4>"),
    ("<h4>Meer</h4>", "<h4>Mehr</h4>"),
    ('<a href="#praktisch">Praktische info</a>', '<a href="#praktisch">Praktische Infos</a>'),
    ("Niederau.nl · Onafhankelijke site, niet verbonden aan officiële instanties.</p>", "Niederau.nl · Unabhängige Seite, nicht mit offiziellen Stellen verbunden.</p>"),
]

T["en"] += [
    ("// Seizoen: 1 okt t/m 31 mrt = winter, 1 apr t/m 30 sep = zomer", "// Season: 1 Oct – 31 Mar = winter, 1 Apr – 30 Sep = summer"),
    ('aria-label="Wissel tussen zomer- en winterversie" title="Wissel tussen zomer- en winterversie"><span data-only="winter">☀ Zomer</span>',
     'aria-label="Switch between summer and winter version" title="Switch between summer and winter version"><span data-only="winter">☀ Summer</span>'),
    ("❄ Winterseizoen: pistes vanuit het dorp, rodelen en knisperende wintermiddagen.", "❄ Winter season: slopes from the village, tobogganing and crisp winter afternoons."),
    ("☀ Zomerseizoen: almen, bergwandelingen en lange avonden op het terras.", "☀ Summer season: alpine pastures, mountain hikes and long evenings on the terrace."),
]
T["de"] += [
    ("// Seizoen: 1 okt t/m 31 mrt = winter, 1 apr t/m 30 sep = zomer", "// Saison: 1. Okt. – 31. März = Winter, 1. Apr. – 30. Sep. = Sommer"),
    ('aria-label="Wissel tussen zomer- en winterversie" title="Wissel tussen zomer- en winterversie"><span data-only="winter">☀ Zomer</span>',
     'aria-label="Zwischen Sommer- und Winterversion wechseln" title="Zwischen Sommer- und Winterversion wechseln"><span data-only="winter">☀ Sommer</span>'),
    ("❄ Winterseizoen: pistes vanuit het dorp, rodelen en knisperende wintermiddagen.", "❄ Wintersaison: Pisten direkt vom Dorf, Rodeln und klare Winternachmittage."),
    ("☀ Zomerseizoen: almen, bergwandelingen en lange avonden op het terras.", "☀ Sommersaison: Almen, Bergwanderungen und lange Abende auf der Terrasse."),
]

NL_STAY = [
    "Aanbevolen verblijf</p>",
    "Wie Niederau wil beleven, zit bij Hotel Wastlhof midden in het dorp – met de bergen achter het huis, in de winter én in de zomer.",
    "Hotel Wastlhof in de sneeuw bij avond, met verlichte gevel",
    "Hotel Wastlhof in de zomer, gezien vanuit een bloeiende bergweide",
    "Hotel Wastlhof op een zonnige winterdag met besneeuwde hellingen erachter",
    "Ligweide met rode parasols in de tuin van Hotel Wastlhof",
    "Hotel Wastlhof op een zomeravond, met verlichte balkons",
    '<span class="ad-label">Partner</span>',
    "Waarom Hotel Wastlhof?",
    "Midden in Niederau, met pistes, wandelpaden en het dorpscentrum dichtbij",
    "In de winter een sneeuwdecor vanaf de voordeur",
    "Buitenzwembad met ligweide en parasols, met de bergen als decor",
    "Typisch Tiroolse bouw met bloemrijke balkons en uitzicht op de bergen",
    "<li>Website en informatie ook in het Nederlands</li>",
    'href="https://www.hotelwastlhof.at/nl/"',
    ">Bekijk Hotel Wastlhof</a>",
    "Partner: Niederau.nl werkt samen met Hotel Wastlhof. Kijk voor prijzen, faciliteiten en beschikbaarheid op de website van het hotel.",
]
EN_STAY = [
    "Recommended stay</p>",
    "If you want to experience Niederau, Hotel Wastlhof puts you right in the heart of the village – with the mountains behind the house, in winter and in summer.",
    "Hotel Wastlhof in the snow in the evening, with its facade lit up",
    "Hotel Wastlhof in summer, seen from a flowering mountain meadow",
    "Hotel Wastlhof on a sunny winter day with snowy slopes behind",
    "Sunbathing lawn with red parasols in the garden of Hotel Wastlhof",
    "Hotel Wastlhof on a summer evening, with lit balconies",
    '<span class="ad-label">Partner</span>',
    "Why Hotel Wastlhof?",
    "Right in Niederau, with slopes, footpaths and the village centre close by",
    "In winter, a snowy scene right from the front door",
    "Outdoor pool with sun lawn and parasols, framed by the mountains",
    "Classic Tyrolean architecture with flower-filled balconies and mountain views",
    "<li>Information available in several languages, including English</li>",
    'href="https://www.hotelwastlhof.at/"',
    ">Visit Hotel Wastlhof</a>",
    "Partner: Niederau.nl works together with Hotel Wastlhof. For prices, facilities and availability, see the hotel’s website.",
]
DE_STAY = [
    "Unterkunftstipp</p>",
    "Wer Niederau erleben möchte, wohnt im Hotel Wastlhof mitten im Dorf – mit den Bergen hinterm Haus, im Winter wie im Sommer.",
    "Hotel Wastlhof im Schnee am Abend, mit beleuchteter Fassade",
    "Hotel Wastlhof im Sommer, von einer blühenden Bergwiese aus gesehen",
    "Hotel Wastlhof an einem sonnigen Wintertag mit verschneiten Hängen dahinter",
    "Liegewiese mit roten Sonnenschirmen im Garten des Hotel Wastlhof",
    "Hotel Wastlhof an einem Sommerabend, mit beleuchteten Balkonen",
    '<span class="ad-label">Partner</span>',
    "Warum Hotel Wastlhof?",
    "Mitten in Niederau, mit Pisten, Wanderwegen und Ortszentrum in der Nähe",
    "Im Winter Schneekulisse direkt vor der Haustür",
    "Freibecken mit Liegewiese und Sonnenschirmen, die Berge als Kulisse",
    "Typisch Tiroler Bauweise mit blumengeschmückten Balkonen und Bergblick",
    "<li>Informationen auch auf Niederländisch und Englisch</li>",
    'href="https://www.hotelwastlhof.at/"',
    ">Hotel Wastlhof ansehen</a>",
    "Partner: Niederau.nl arbeitet mit dem Hotel Wastlhof zusammen. Preise, Ausstattung und Verfügbarkeit finden Sie auf der Website des Hotels.",
]
T["en"] += list(zip(NL_STAY, EN_STAY)) + [
    ('<a href="#stay">Verblijf</a>', '<a href="#stay">Where to stay</a>'),
    ("Hotel Wastlhof in Niederau</h2>", "Hotel Wastlhof in Niederau</h2>"),
]
T["de"] += list(zip(NL_STAY, DE_STAY)) + [
    ('<a href="#unterkunft">Verblijf</a>', '<a href="#unterkunft">Unterkunft</a>'),
]

T["en"] += [('<a href="https://www.wildschoenau.com/"', '<a href="https://www.wildschoenau.com/en"')]

GAL_NL = ["Buitenzwembad dat ook in de winter open is: zwemmen tussen de sneeuw", "<li>Viersterrenhotel met wellness</li>",
  "Zwembad &amp; wellness</h3>",
  "Kind springt in het buitenzwembad van Hotel Wastlhof, met parasols en bergen op de achtergrond",
  "Twee gasten aan de rand van het buitenzwembad van Hotel Wastlhof",
  "Wellnessvleugel van Hotel Wastlhof met glazen serre en verlicht buitenzwembad in de sneeuw",
  "Buitenzwembad van Hotel Wastlhof in een besneeuwd landschap",
  "Badslippers en handdoeken van Hotel Wastlhof bij het zwembad"]
GAL_EN = ["Outdoor pool that stays open in winter: swimming surrounded by snow", "<li>Four-star hotel with wellness area</li>",
  "Pool &amp; wellness</h3>",
  "Child jumping into the outdoor pool of Hotel Wastlhof, with parasols and mountains behind",
  "Two guests at the edge of the outdoor pool of Hotel Wastlhof",
  "Wellness wing of Hotel Wastlhof with glass conservatory and lit outdoor pool in the snow",
  "Outdoor pool of Hotel Wastlhof in a snowy landscape",
  "Hotel Wastlhof slippers and towels by the pool"]
GAL_DE = ["Freibecken, das auch im Winter geöffnet ist: Schwimmen mitten im Schnee", "<li>Vier-Sterne-Hotel mit Wellnessbereich</li>",
  "Pool &amp; Wellness</h3>",
  "Kind springt in das Freibecken des Hotel Wastlhof, mit Sonnenschirmen und Bergen im Hintergrund",
  "Zwei Gäste am Beckenrand des Freibeckens im Hotel Wastlhof",
  "Wellnessbereich des Hotel Wastlhof mit Glaswintergarten und beleuchtetem Freibecken im Schnee",
  "Freibecken des Hotel Wastlhof in verschneiter Landschaft",
  "Badeschuhe und Handtücher des Hotel Wastlhof am Pool"]
T["en"] += list(zip(GAL_NL, GAL_EN))
T["de"] += list(zip(GAL_NL, GAL_DE))

OBSOLETE = {
    '<a href="#practical">Praktisch</a>',
    '<a href="#practical">Practical</a>', '<a href="#praktisch">Praktisch</a>',
    "Wandelaars kijken uit over het groene hoogdal van de Wildschönau in de zomer",
    "Brettljause op een almterras met uitzicht over de Kitzbüheler Alpen in de Wildschönau",
    "<li>Paardrijden vanuit het hotel, in de zomer én in de winter</li>",
    '"url": "https://niederau.nl/",', '"inLanguage": "nl",',
    '"description": "Bergdorp in de Wildschönau, Tirol, Oostenrijk.",',
    '"name": "Wildschönau, Tirol, Oostenrijk"', '"touristType": ["Wintersport", "Wandelen", "Gezinnen"]',
    '<p>De Wildschönau is een zijdal van het Inndal, hoog boven Wörgl. Elk dorp heeft zijn eigen karakter.</p>',
    "Wie Niederau wil beleven, zit bij Hotel Wastlhof midden in het dorp – met de bergen achter het huis, in de winter én in de zomer.",
    "Midden in Niederau, met pistes, wandelpaden en het dorpscentrum dichtbij",
    "In de winter een sneeuwdecor vanaf de voordeur",
    "Buitenzwembad met ligweide en parasols, met de bergen als decor",
    "Typisch Tiroolse bouw met bloemrijke balkons en uitzicht op de bergen",
    "<li>Viersterrenhotel met wellness</li>",
    "Ook sneeuwschoenwandelen en rodelen zijn populair: het dal telt drie rodelbanen, die van het Lahnerköpfl ligt in Niederau zelf.</p>",
    "De Wildschönau is ingericht op gezinnen. Aan de rand van Niederau ligt een openluchtzwembad met drie bassins en een grote glijbaan.</p>",
}
HOTEL_NL = [
    "<p>Een viersterrenhotel met wellness, gerund door een familie, aan de doorgaande weg door Niederau. De pistes, loipes en wandelpaden beginnen vrijwel naast de deur.</p>",
    "<li>Familiebedrijf en viersterren-wellnesshotel midden in Niederau</li>",
    "Skigebied vanaf de voordeur: na het skiën ben je meteen weer thuis",
    "Langlaufloipes beginnen bij het hotel; de rodelbaan Lahnerköpfl ligt vlak voor de deur (rodels te huur)",
    "Skiguiding: gastvrouw Margit neemt je mee naar haar favoriete pistes",
    "Relax-tuin met royaal buitenzwembad, ligweide en parasols",
    "Gasten tennissen gratis op het tenniscomplex van de Wildschönau",
    "Kamers, appartementen en suites in het hotel en de nieuwe Alpin Lodge",
    ">Bel het hotel</a>",
    "6314 Wildschönau, Oostenrijk",
]
HOTEL_EN = [
    "<p>A family-run four-star hotel with wellness facilities on the main road through Niederau. Slopes, cross-country trails and footpaths start practically next door.</p>",
    "<li>Family-run four-star wellness hotel in the centre of Niederau</li>",
    "Ski from the front door: after skiing you are straight back home",
    "Cross-country trails begin by the hotel, and the Lahnerköpfl toboggan run is a few steps away (sledges to rent)",
    "Ski guiding: hostess Margit takes you to her favourite slopes",
    "Relaxation garden with a generous outdoor pool, sun lawn and parasols",
    "Guests play tennis free of charge at the Wildschönau tennis complex",
    "Rooms, apartments and suites in the hotel and the new Alpin Lodge",
    ">Call the hotel</a>",
    "6314 Wildschönau, Austria",
]
HOTEL_DE = [
    "<p>Ein familiengeführtes Vier-Sterne-Hotel mit Wellness an der Durchgangsstraße von Niederau. Pisten, Loipen und Wanderwege beginnen praktisch nebenan.</p>",
    "<li>Familienbetrieb und Vier-Sterne-Wellnesshotel mitten in Niederau</li>",
    "Skigebiet ab der Haustür: nach dem Skifahren gleich wieder daheim",
    "Langlaufloipen starten beim Hotel; die Rodelbahn Lahnerköpfl liegt direkt vor der Tür (Rodelverleih)",
    "Skiguiding: Gastgeberin Margit zeigt Ihnen ihre Lieblingspisten",
    "Relax-Garten mit großzügigem Freibecken, Liegewiese und Sonnenschirmen",
    "Gäste spielen gratis Tennis auf der Wildschönauer Tennisanlage",
    "Zimmer, Appartements und Suiten im Hotel und in der neuen Alpin Lodge",
    ">Hotel anrufen</a>",
    "6314 Wildschönau, Österreich",
]
T["en"] += list(zip(HOTEL_NL, HOTEL_EN))
T["de"] += list(zip(HOTEL_NL, HOTEL_DE))

T["en"] += [("<li>Paardrijden vanuit het hotel, in de zomer én in de winter</li>", "<li>Horse riding from the hotel, in summer and in winter</li>")]
T["de"] += [("<li>Paardrijden vanuit het hotel, in de zomer én in de winter</li>", "<li>Reiten direkt vom Hotel aus, im Sommer wie im Winter</li>")]

T['en'] += [('<p>Het hoogdal Wildschönau ligt in de Kitzbüheler Alpen en staat bekend als een zonnige en sneeuwzekere bestemming. Mede dankzij de vriendelijke uitstraling won het dal de eerste prijs van de ADAC – de Duitse ANWB – in de categorie “Klein &amp; Fein”.</p>\n      <p>De Wildschönau bestaat uit de vier kerkdorpen Niederau, Oberau, Auffach en Thierbach, plus het gehucht Mühltal. Het dal is bij uitstek geschikt voor ontspannen skiën midden in een prachtige bergwereld. De regio is altijd goed bereikbaar, ligt niet ver van Kufstein en biedt naast traditionele wintersport ook een veelzijdig zomeraanbod.</p>', '<p>The Wildschönau high valley lies in the Kitzbühel Alps and is known as a sunny, snow-sure destination. Thanks in part to its friendly character, the valley won first prize from the ADAC – Germany’s largest motoring club – in the “Klein &amp; Fein” (small and fine) category.</p>\n      <p>The Wildschönau is made up of four church villages – Niederau, Oberau, Auffach and Thierbach – plus the hamlet of Mühltal. The valley is ideal for relaxed skiing amid a magnificent mountain landscape. Always easy to reach and not far from Kufstein, it offers a varied summer programme as well as traditional winter sports.</p>')]
T['de'] += [('<p>Het hoogdal Wildschönau ligt in de Kitzbüheler Alpen en staat bekend als een zonnige en sneeuwzekere bestemming. Mede dankzij de vriendelijke uitstraling won het dal de eerste prijs van de ADAC – de Duitse ANWB – in de categorie “Klein &amp; Fein”.</p>\n      <p>De Wildschönau bestaat uit de vier kerkdorpen Niederau, Oberau, Auffach en Thierbach, plus het gehucht Mühltal. Het dal is bij uitstek geschikt voor ontspannen skiën midden in een prachtige bergwereld. De regio is altijd goed bereikbaar, ligt niet ver van Kufstein en biedt naast traditionele wintersport ook een veelzijdig zomeraanbod.</p>', '<p>Das Hochtal Wildschönau liegt in den Kitzbüheler Alpen und gilt als sonniges und schneesicheres Urlaubsziel. Nicht zuletzt dank seiner freundlichen Ausstrahlung erhielt das Tal den ersten Preis des ADAC in der Kategorie „Klein &amp; Fein“.</p>\n      <p>Die Wildschönau besteht aus den vier Kirchdörfern Niederau, Oberau, Auffach und Thierbach sowie dem Weiler Mühltal. Das Tal eignet sich besonders für entspanntes Skifahren inmitten einer herrlichen Bergwelt. Die stets gut erreichbare Urlaubsregion liegt nicht weit von Kufstein und bietet neben dem klassischen Wintersport auch ein vielseitiges Sommerangebot.</p>')]

EIGEN_NL = ["Niederau in beeld</h3>",
  "Uitzicht op de besneeuwde pistes en liften van Niederau bij winterzon",
  "Oefenlift en skihut aan de voet van de piste in Niederau, na verse sneeuwval",
  "Snowboarder op een zonnige helling in Niederau"]
EIGEN_EN = ["Niederau in pictures</h3>",
  "View of the snowy slopes and lifts of Niederau in winter sunshine",
  "Beginners’ lift and ski hut at the foot of the slope in Niederau, after fresh snowfall",
  "Snowboarder on a sunny slope in Niederau"]
EIGEN_DE = ["Niederau in Bildern</h3>",
  "Blick auf die verschneiten Pisten und Lifte von Niederau bei Wintersonne",
  "Übungslift und Skihütte am Fuß der Piste in Niederau nach frischem Neuschnee",
  "Snowboarder an einem sonnigen Hang in Niederau"]
T["en"] += list(zip(EIGEN_NL, EIGEN_EN))
T["de"] += list(zip(EIGEN_NL, EIGEN_DE))

CARD_NL = "<p>Met de Wildschönau Premium Card gebruik je in de zomer de bergbanen gratis. Vraag bij je accommodatie of die de kaart aanbiedt.</p>"
T["en"] += [(CARD_NL, "<p>With the Wildschönau Premium Card the mountain lifts are free in summer. Ask your accommodation whether it offers the card.</p>")]
T["de"] += [(CARD_NL, "<p>Mit der Wildschönau Premium Card fahren Sie im Sommer gratis mit den Bergbahnen. Fragen Sie Ihre Unterkunft, ob sie die Karte anbietet.</p>")]

HIST_NL = [
 ('<a href="#history">Geschiedenis</a>', '<a href="#history">History</a>', '<a href="#geschichte">Geschiedenis</a>', '<a href="#geschichte">Geschichte</a>'),
]
for nl_en, en, nl_de, de in HIST_NL:
    T["en"].append((nl_en, en)); T["de"].append((nl_de, de))
H_NL = [
 '<p class="eyebrow">Geschiedenis</p>',
 "Van boerendal tot wintersportdorp</h2>",
 "<p>Niederau ligt in de Wildschönau, een hoogdal in Tirol (Oostenrijk). Eeuwenlang was het een afgelegen dal van boeren en mijnwerkers. Pas in de twintigste eeuw kwamen de eerste toeristen – en in 1947 begon in Niederau met de eerste stoeltjeslift van Tirol het wintersporttijdperk van het dal.</p>",
 "<p>Die lift was een kunststuk: ingenieur Sepp Hochmuth bouwde hem vlak na de Tweede Wereldoorlog, volgens de overlevering met motoren en aandrijfwielen van tanks die bij het station van Wörgl waren achtergelaten. Op 14 januari 1947 ging hij open, van Niederau naar het Markbachjoch.</p>",
 "<br>Eerste schriftelijke vermelding van de Wildschönau.</li>",
 '<span class="when">16e eeuw</span><br>Mijnbouw: op de hellingen van de Gratlspitz bij Thierbach wordt zilver- en kopererts gewonnen.</li>',
 '<span class="when">18e eeuw</span><br>Keizerin Maria Theresia verleent 51 boeren in het dal het stookrecht voor Krautinger. Vandaag stoken er nog zo’n vijftien.</li>',
 "<br>De Wildschönau wordt een zelfstandige gemeente.</li>",
 '<span class="when">Begin 20e eeuw</span><br>Een weg door de Kundler Klamm verbindt het dal met het Inndal; de overdekte houten brug dateert van 1913/14. Het huidige wandelpad volgt die oude weg.</li>',
 '<span class="when">14 januari 1947</span><br>De eerste stoeltjeslift van Tirol opent in Niederau, naar het Markbachjoch. Het begin van het toerisme in het dal.</li>',
 "<br>Een gondelbaan voor acht personen vervangt de oude stoeltjeslift: de huidige Markbachjochbahn.</li>",
 "<br>De bergbaan in Niederau viert haar 75-jarig jubileum.</li>",
]
H_EN = [
 '<p class="eyebrow">History</p>',
 "From farming valley to ski village</h2>",
 "<p>Niederau lies in the Wildschönau, a high valley in Tyrol (Austria). For centuries it was a remote valley of farmers and miners. The first tourists only arrived in the twentieth century – and in 1947 the valley’s winter sports era began in Niederau with the first chairlift in Tyrol.</p>",
 "<p>That lift was quite a feat: engineer Sepp Hochmuth built it just after the Second World War, according to local lore using engines and drive wheels from tanks abandoned at Wörgl station. It opened on 14 January 1947, running from Niederau up to the Markbachjoch.</p>",
 "<br>First written mention of the Wildschönau.</li>",
 '<span class="when">16th century</span><br>Mining: silver and copper ore is extracted on the slopes of the Gratlspitz near Thierbach.</li>',
 '<span class="when">18th century</span><br>Empress Maria Theresa gives 51 farmers in the valley the right to distil Krautinger. Some fifteen still do so today.</li>',
 "<br>The Wildschönau becomes an independent municipality.</li>",
 '<span class="when">Early 20th century</span><br>A road through the Kundler Klamm links the valley with the Inn valley; the covered wooden bridge dates from 1913/14. Today’s footpath follows that old road.</li>',
 '<span class="when">14 January 1947</span><br>Tyrol’s first chairlift opens in Niederau, up to the Markbachjoch. The start of tourism in the valley.</li>',
 "<br>An eight-seater gondola replaces the old chairlift: today’s Markbachjochbahn.</li>",
 "<br>The mountain railway in Niederau celebrates its 75th anniversary.</li>",
]
H_DE = [
 '<p class="eyebrow">Geschichte</p>',
 "Vom Bauerntal zum Skidorf</h2>",
 "<p>Niederau liegt in der Wildschönau, einem Hochtal in Tirol (Österreich). Jahrhundertelang war es ein abgelegenes Tal der Bauern und Bergknappen. Erst im 20. Jahrhundert kamen die ersten Gäste – und 1947 begann in Niederau mit dem ersten Sessellift Tirols das Wintersportzeitalter des Tals.</p>",
 "<p>Dieser Lift war ein Kunststück: Ing. Sepp Hochmuth baute ihn kurz nach dem Zweiten Weltkrieg, der Überlieferung nach mit Motoren und Antriebsrädern von Panzern, die am Bahnhof Wörgl zurückgelassen worden waren. Am 14. Jänner 1947 wurde er eröffnet, von Niederau hinauf zum Markbachjoch.</p>",
 "<br>Erste urkundliche Erwähnung der Wildschönau.</li>",
 '<span class="when">16. Jahrhundert</span><br>Bergbau: An den Hängen der Gratlspitz bei Thierbach werden Silber- und Kupfererze abgebaut.</li>',
 '<span class="when">18. Jahrhundert</span><br>Kaiserin Maria Theresia gibt 51 Bauern im Tal das Brennrecht für Krautinger. Heute brennen noch etwa fünfzehn.</li>',
 "<br>Die Wildschönau wird eine eigenständige Gemeinde.</li>",
 '<span class="when">Anfang 20. Jahrhundert</span><br>Eine Straße durch die Kundler Klamm verbindet das Tal mit dem Inntal; die überdachte Holzbrücke stammt von 1913/14. Der heutige Wanderweg folgt dieser alten Straße.</li>',
 '<span class="when">14. Jänner 1947</span><br>In Niederau eröffnet der erste Sessellift Tirols, hinauf zum Markbachjoch. Der Beginn des Tourismus im Tal.</li>',
 "<br>Eine Achter-Gondelbahn ersetzt den alten Sessellift: die heutige Markbachjochbahn.</li>",
 "<br>Die Bergbahn in Niederau feiert ihr 75-jähriges Jubiläum.</li>",
]
T["en"] += list(zip(H_NL, H_EN))
T["de"] += list(zip(H_NL, H_DE))

Z_NL = ["Wandelaars kijken uit over het groene hoogdal van de Wildschönau in de zomer",
        "Brettljause op een almterras met uitzicht over de Kitzbüheler Alpen in de Wildschönau"]
Z_EN = ["Hikers looking out over the green Wildschönau high valley in summer",
        "Brettljause on an alpine hut terrace with views over the Kitzbühel Alps in the Wildschönau"]
Z_DE = ["Wanderer blicken im Sommer über das grüne Hochtal der Wildschönau",
        "Brettljause auf einer Almterrasse mit Blick über die Kitzbüheler Alpen in der Wildschönau"]
T["en"] += list(zip(Z_NL, Z_EN))
T["de"] += list(zip(Z_NL, Z_DE))

# --- Ontwerp met foto's (hotelstijl) ---
P = [
 ("Skiërs op de zonnige pistes van het Markbachjoch boven Niederau", "Skiers on the sunny slopes of the Markbachjoch above Niederau", "Skifahrer auf den sonnigen Pisten am Markbachjoch über Niederau"),
 ("Gezin skiet in Ski Juwel Alpbachtal Wildschönau", "Family skiing in Ski Juwel Alpbachtal Wildschönau", "Familie beim Skifahren im Ski Juwel Alpbachtal Wildschönau"),
 ("Kinderen leren skiën in de Wildschönau", "Children learning to ski in the Wildschönau", "Kinder lernen Skifahren in der Wildschönau"),
 ("Langlaufloipe door het besneeuwde dal van de Wildschönau", "Cross-country trail through the snowy Wildschönau valley", "Langlaufloipe durch das verschneite Tal der Wildschönau"),
 ("Pauze op een zonnig terras in het skigebied", "A break on a sunny terrace in the ski area", "Pause auf einer sonnigen Terrasse im Skigebiet"),
 ("Winterwandelaars in de zon boven het dal van de Wildschönau", "Winter walkers in the sun above the Wildschönau valley", "Winterwanderer in der Sonne über dem Tal der Wildschönau"),
 ("Gezin wandelt over een bergweide in de Wildschönau", "Family hiking across a mountain meadow in the Wildschönau", "Familie wandert über eine Bergwiese in der Wildschönau"),
 ("E-bikers op een grindweg met uitzicht over het dal", "E-bikers on a gravel track overlooking the valley", "E-Biker auf einem Schotterweg mit Blick über das Tal"),
 ("Brettljause op een almterras met uitzicht over de Kitzbüheler Alpen", "Brettljause on an alpine hut terrace overlooking the Kitzbühel Alps", "Brettljause auf einer Almterrasse mit Blick über die Kitzbüheler Alpen"),
 ("Openluchtzwembad met glijbaan tussen Niederau en Oberau", "Open-air pool with water slide between Niederau and Oberau", "Freibad mit Rutsche zwischen Niederau und Oberau"),
 ("Optocht met muziekkapel tijdens het Talfest in Niederau", "Procession with brass band during the Talfest in Niederau", "Festumzug mit Musikkapelle beim Talfest in Niederau"),
 ("Wandelaars kijken uit over het groene hoogdal van de Wildschönau\"", "Hikers looking out over the green Wildschönau high valley\"", "Wanderer blicken über das grüne Hochtal der Wildschönau\""),
 ("Niederau in de winter met de sleeplift aan de rand van het dorp", "Niederau in winter with the drag lift on the edge of the village", "Niederau im Winter mit dem Schlepplift am Ortsrand"),
 ("Winterlandschap bij Oberau in de Wildschönau", "Winter landscape near Oberau in the Wildschönau", "Winterlandschaft bei Oberau in der Wildschönau"),
 ("Fietsers op een weg door de weiden bij Auffach", "Cyclists on a road through the meadows near Auffach", "Radfahrer auf einem Weg durch die Wiesen bei Auffach"),
 ("Sneeuwschoenwandelaars in de zon bij Thierbach", "Snowshoe hikers in the sun near Thierbach", "Schneeschuhwanderer in der Sonne bei Thierbach"),
 ("Fles Wildschönauer Krautinger met twee glaasjes op een houten balustrade", "Bottle of Wildschönauer Krautinger with two glasses on a wooden railing", "Flasche Wildschönauer Krautinger mit zwei Gläsern auf einem Holzgeländer"),
 ("Kaiserschmarrn met poedersuiker en vruchtencompote", "Kaiserschmarrn with icing sugar and fruit compote", "Kaiserschmarrn mit Staubzucker und Fruchtkompott"),
 ("Gondel van de Markbachjochbahn boven Niederau met uitzicht over de Alpen", "Markbachjochbahn gondola above Niederau with views over the Alps", "Gondel der Markbachjochbahn über Niederau mit Blick über die Alpen"),
 ("Wandelaars op een bergpad hoog boven de Wildschönau", "Hikers on a mountain path high above the Wildschönau", "Wanderer auf einem Bergweg hoch über der Wildschönau"),
 ("Kapel bij de Schönangeralm met bergpanorama in de zomer", "Chapel at the Schönangeralm with mountain panorama in summer", "Kapelle bei der Schönangeralm mit Bergpanorama im Sommer"),
 ("Paardenkoets in de optocht van het Talfest in Niederau", "Horse-drawn carriage in the Talfest procession in Niederau", "Pferdekutsche im Festumzug des Talfests in Niederau"),
 ("<p>Samen 145 km piste, 47 liften, 24 skihutten en drie snowparks.</p>", "<p>Together 145 km of slopes, 47 lifts, 24 ski huts and three snow parks.</p>", "<p>Insgesamt 145 Pistenkilometer, 47 Lifte, 24 Skihütten und drei Snowparks.</p>"),
 ("<p>De Penningberg-loipe (12 km) begint in Niederau; in het hele dal liggen zo’n 30 tot 40 km loipes.</p>", "<p>The Penningberg trail (12 km) starts in Niederau; the whole valley has some 30 to 40 km of cross-country trails.</p>", "<p>Die Penningberg-Loipe (12 km) beginnt in Niederau; im ganzen Tal gibt es rund 30 bis 40 km Loipen.</p>"),
 ("<p>Het dal telt meer dan 300 km gemarkeerde wandelpaden.</p>", "<p>The valley has more than 300 km of waymarked trails.</p>", "<p>Das Tal hat mehr als 300 km markierte Wanderwege.</p>"),
 ("<p>Tussen Niederau en Oberau ligt een verwarmd openluchtbad: ruim 1.000 m² wateroppervlak, verdeeld over drie baden.</p>", "<p>Between Niederau and Oberau there is a heated outdoor pool complex: well over 1,000 m² of water spread across three pools.</p>", "<p>Zwischen Niederau und Oberau liegt ein beheiztes Freibad: gut 1.000 m² Wasser, aufgeteilt auf drei Becken.</p>"),
 ("<p>Hoogtepunt is het Talfest in augustus, afwisselend in Niederau, Oberau en Auffach, met een grote optocht.</p>", "<p>The highlight is the Talfest in August, held in turn in Niederau, Oberau and Auffach, with a big procession.</p>", "<p>Höhepunkt ist das Talfest im August – jedes Jahr in einem anderen Dorf (Niederau, Oberau oder Auffach), mit einem langen Festumzug.</p>"),
 ("<p>Je krijgt de kaart bij deelnemende accommodaties. Daarmee rijd je ook gratis met de wandelbus, zwem je in de openluchtbaden, bezoek je het Bergbauernmuseum z’Bach in Oberau en kunnen kinderen (5–14 jaar) mee met de Drachenclub.</p>", "<p>You get the card from participating accommodation. It also gets you onto the hiking bus, into the outdoor pools and the Bergbauernmuseum z’Bach in Oberau, and lets children (5–14) join the Drachenclub.</p>", "<p>Die Karte erhalten Sie bei teilnehmenden Unterkünften. Damit fahren Sie außerdem mit dem Wanderbus, baden in den Freibädern, besuchen das Bergbauernmuseum z’Bach in Oberau, und Kinder (5–14) können beim Drachenclub mitmachen.</p>"),
 ("<li>Al drie generaties gerund door de familie Brunner</li>", "<li>Run by the Brunner family for three generations</li>", "<li>Seit drei Generationen von Familie Brunner geführt</li>"),
 ("<li>Eigen manege met zo’n 15 paarden, waaronder Haflingers – al meer dan 50 jaar</li>", "<li>Own riding stables with some 15 horses, including Haflingers – for more than 50 years</li>", "<li>Eigener Reitstall mit rund 15 Pferden, darunter Haflinger – seit mehr als 50 Jahren</li>"),
 ("<li>Binnenzwembad (12 × 6 m, ca. 30 °C) en een buitenzwembad dat het hele jaar verwarmd is</li>", "<li>Indoor pool (12 × 6 m, approx. 30 °C) and an outdoor pool heated all year round</li>", "<li>Hallenbad (12 × 6 m, ca. 30 °C) und ein ganzjährig beheiztes Freibecken</li>"),
 ("<p class=\"credits\">Foto’s: Wildschönau Tourismus (H. Dabernig, shoot&amp;style, A. Mayr, J. Ehammer), AMTirol, Ski Juwel Alpbachtal Wildschönau, Wildschönauer Bergbahnen, Hotel Wastlhof en eigen foto’s.</p>",
  "<p class=\"credits\">Photos: Wildschönau Tourismus (H. Dabernig, shoot&amp;style, A. Mayr, J. Ehammer), AMTirol, Ski Juwel Alpbachtal Wildschönau, Wildschönauer Bergbahnen, Hotel Wastlhof and own photos.</p>",
  "<p class=\"credits\">Fotos: Wildschönau Tourismus (H. Dabernig, shoot&amp;style, A. Mayr, J. Ehammer), AMTirol, Ski Juwel Alpbachtal Wildschönau, Wildschönauer Bergbahnen, Hotel Wastlhof und eigene Fotos.</p>"),
]
T["en"] += [(a, b) for a, b, c in P]
T["de"] += [(a, c) for a, b, c in P]

L = [
 ("De huisberg van Niederau</h2>", "Niederau’s home mountain</h2>", "Der Hausberg von Niederau</h2>"),
 ("<p>Direct boven het dorp rijst het Lanerköpfl op – door het hotel en veel bewoners ook Lahnerköpfl genoemd. Samen met het Markbachjoch vormt het het skigebied van Niederau, met afdalingen die tot in het dorp eindigen.</p>",
  "<p>Right above the village rises the Lanerköpfl – also written Lahnerköpfl by the hotel and many locals. Together with the Markbachjoch it forms Niederau’s ski area, with runs that end in the village.</p>",
  "<p>Direkt über dem Dorf erhebt sich das Lanerköpfl – vom Hotel und vielen Einheimischen auch Lahnerköpfl geschrieben. Zusammen mit dem Markbachjoch bildet es das Skigebiet von Niederau, mit Abfahrten bis ins Dorf.</p>"),
 ("<p><strong>De lift.</strong> Jarenlang bracht een eenpersoons stoeltjeslift de skiërs naar boven. Sinds het seizoen 2008/09 rijdt de Lanerköpflbahn: een snelle vierpersoons stoeltjeslift met kap, van het dalstation op 843 m naar het bergstation op 1.560 m – in zo’n zeven minuten, met plaats voor 1.400 personen per uur.</p>",
  "<p><strong>The lift.</strong> For many years a single chairlift carried skiers up. Since the 2008/09 season the Lanerköpflbahn has been running: a fast four-seater chairlift with bubble, from the valley station at 843 m to the top station at 1,560 m – in about seven minutes, with room for 1,400 people per hour.</p>",
  "<p><strong>Der Lift.</strong> Jahrelang brachte ein Einersessellift die Skifahrer nach oben. Seit der Saison 2008/09 fährt die Lanerköpflbahn: eine kuppelbare Vierersesselbahn mit Haube, von der Talstation auf 843 m zur Bergstation auf 1.560 m – in rund sieben Minuten, mit einer Förderleistung von 1.400 Personen pro Stunde.</p>"),
 ("<p><strong>De afdaling.</strong> De noordhellingen van het Lanerköpfl en het Markbachjoch staan bekend als uitdagend; vooral de Hochberg-afdaling vraagt ook van ervaren skiërs het nodige. Wie het rustiger aan wil doen, oefent beneden op de sleeplift en de oefenweiden aan de rand van het dorp.</p>",
  "<p><strong>The descent.</strong> The north slopes of the Lanerköpfl and the Markbachjoch are known as challenging; the Hochberg run in particular tests even experienced skiers. If you prefer to take it easy, practise down below on the drag lift and the nursery slopes on the edge of the village.</p>",
  "<p><strong>Die Abfahrt.</strong> Die Nordhänge von Lanerköpfl und Markbachjoch gelten als anspruchsvoll; vor allem die Hochberg-Abfahrt fordert auch geübte Skifahrer. Wer es ruhiger angehen will, übt unten am Schlepplift und auf den Übungswiesen am Ortsrand.</p>"),
 ("<p><strong>De rodelbaan.</strong> Het Lanerköpfl is ook de rodelberg van Niederau: vanaf het bergstation loopt een natuurrodelbaan van bijna 6 km langs de Gseng-Alm en de Laner-Alm terug naar het dalstation. Met 736 m hoogteverschil en gemiddeld 14% helling is het een sportieve baan.</p>",
  "<p><strong>The toboggan run.</strong> The Lanerköpfl is also Niederau’s toboggan mountain: from the top station a natural toboggan run of almost 6 km leads past the Gseng-Alm and the Laner-Alm back to the valley station. With 736 m of descent and an average gradient of 14% it is a sporty run.</p>",
  "<p><strong>Die Rodelbahn.</strong> Das Lanerköpfl ist auch der Rodelberg von Niederau: Von der Bergstation führt eine fast 6 km lange Naturrodelbahn vorbei an Gseng-Alm und Laner-Alm zurück zur Talstation. Mit 736 m Höhenunterschied und durchschnittlich 14 % Gefälle ist sie eine sportliche Bahn.</p>"),
 ("Sleeplift, skihut en pistes aan de voet van het Lanerköpfl in Niederau na verse sneeuw", "Drag lift, ski hut and slopes at the foot of the Lanerköpfl in Niederau after fresh snow", "Schlepplift, Skihütte und Pisten am Fuß des Lanerköpfls in Niederau nach Neuschnee"),
 ('aria-label="Lanerköpfl in cijfers"', 'aria-label="Lanerköpfl in numbers"', 'aria-label="Lanerköpfl in Zahlen"'),
 ("<span>bergstation Lanerköpflbahn</span>", "<span>top station of the Lanerköpflbahn</span>", "<span>Bergstation Lanerköpflbahn</span>"),
 ("<span>dalstation in Niederau</span>", "<span>valley station in Niederau</span>", "<span>Talstation in Niederau</span>"),
 ("<strong>± 7 min</strong><span>naar boven met de vierpersoonslift</span>", "<strong>± 7 min</strong><span>to the top on the four-seater chairlift</span>", "<strong>± 7 Min.</strong><span>Fahrzeit mit der Vierersesselbahn</span>"),
 ("<span>rodelbaan terug naar het dorp</span>", "<span>toboggan run back to the village</span>", "<span>Rodelbahn zurück ins Dorf</span>"),
 ("<br>Op het Lanerköpfl vervangt een snelle vierpersoons stoeltjeslift met kap de oude eenpersoons stoeltjeslift.</li>", "<br>On the Lanerköpfl a fast four-seater chairlift with bubble replaces the old single chairlift.</li>", "<br>Am Lanerköpfl ersetzt eine kuppelbare Vierersesselbahn mit Haube den alten Einersessellift.</li>"),
]
T["en"] += [(a, b) for a, b, c in L]
T["de"] += [(a, c) for a, b, c in L]
T["en"] += [('<a href="#lanerkoepfl">Lanerköpfl</a>', '<a href="#lanerkoepfl">Lanerköpfl</a>')]

ACT = [('<li><strong>Skiën en snowboarden</strong> – vanaf het Markbachjoch en het Lanerköpfl in Niederau, op de Schatzberg in Auffach en via Ski Juwel door tot in Alpbach.</li>', '<li><strong>Skiing and snowboarding</strong> – from the Markbachjoch and Lanerköpfl in Niederau, on the Schatzberg in Auffach and via Ski Juwel all the way to Alpbach.</li>', '<li><strong>Skifahren und Snowboarden</strong> – vom Markbachjoch und Lanerköpfl in Niederau, am Schatzberg in Auffach und über das Ski Juwel bis nach Alpbach.</li>'), ('<li><strong>Rodelen</strong> – op de natuurbaan van het Lanerköpfl of op een van de andere banen in het dal; een slee huur je ter plekke.</li>', '<li><strong>Tobogganing</strong> – on the natural run down from the Lanerköpfl or one of the other runs in the valley; sledges can be rented locally.</li>', '<li><strong>Rodeln</strong> – auf der Naturbahn vom Lanerköpfl oder einer der anderen Bahnen im Tal; Rodeln kann man vor Ort leihen.</li>'), ('<li><strong>Langlaufen</strong> – vlakke loipes door het dal en een hooggelegen loipe bij de Schönangeralm.</li>', '<li><strong>Cross-country skiing</strong> – flat trails along the valley floor and a high-altitude trail at the Schönangeralm.</li>', '<li><strong>Langlaufen</strong> – flache Loipen durchs Tal und eine Höhenloipe bei der Schönangeralm.</li>'), ('<li><strong>Winterwandelen en sneeuwschoenlopen</strong> – over geruimde paden langs boerderijen en kapelletjes, of met een gids door verse sneeuw.</li>', '<li><strong>Winter walks and snowshoeing</strong> – on cleared paths past farms and little chapels, or with a guide through fresh snow.</li>', '<li><strong>Winterwandern und Schneeschuhwandern</strong> – auf geräumten Wegen vorbei an Höfen und Kapellen oder mit einem Führer durch frischen Schnee.</li>'), ('<li><strong>Paardensleetocht</strong> – onder een warme deken door het besneeuwde dal, een klassieker voor jong en oud.</li>', '<li><strong>Horse-drawn sleigh ride</strong> – tucked under a warm blanket through the snowy valley – a classic for young and old.</li>', '<li><strong>Pferdeschlittenfahrt</strong> – unter einer warmen Decke durchs verschneite Tal – ein Klassiker für Groß und Klein.</li>'), ('<li><strong>Schaatsen</strong> – op de ijsbaan in het dal, zolang het koud genoeg is.</li>', '<li><strong>Ice skating</strong> – on the ice rink in the valley, as long as it is cold enough.</li>', '<li><strong>Eislaufen</strong> – auf dem Eisplatz im Tal, solange es kalt genug ist.</li>'), ('<li><strong>Skitoeren</strong> – de zachte, ronde bergen van de Wildschönau zijn geliefd bij toerskiërs. Ga alleen met de juiste uitrusting en kijk eerst naar het lawinebulletin.</li>', '<li><strong>Ski touring</strong> – the soft, rounded mountains of the Wildschönau are popular with ski tourers. Only go with the right equipment and check the avalanche bulletin first.</li>', '<li><strong>Skitouren</strong> – die sanften, runden Berge der Wildschönau sind bei Tourengehern beliebt. Nur mit passender Ausrüstung und nach einem Blick in den Lawinenlagebericht.</li>'), ('<li><strong>Wandelen</strong> – van een rustige ronde door het dal tot tochten over de bergkammen; met de gondel sta je snel hoog.</li>', '<li><strong>Hiking</strong> – from an easy loop through the valley to ridge walks; the gondola gets you up high in no time.</li>', '<li><strong>Wandern</strong> – von der gemütlichen Talrunde bis zur Gratwanderung; mit der Gondel ist man schnell oben.</li>'), ('<li><strong>Kundler Klamm</strong> – wandel door de kloof langs de Wildschönauer Ache naar Kundl in het Inndal en ga met het openbaar vervoer terug.</li>', '<li><strong>Kundler Klamm</strong> – walk through the gorge along the Wildschönauer Ache down to Kundl in the Inn valley and return by public transport.</li>', '<li><strong>Kundler Klamm</strong> – durch die Klamm entlang der Wildschönauer Ache hinunter nach Kundl im Inntal wandern und mit den Öffis zurückfahren.</li>'), ('<li><strong>Fietsen en e-biken</strong> – bosweggen en bergweggetjes naar de almen; fietsen en e-bikes zijn in het dal te huur.</li>', '<li><strong>Cycling and e-biking</strong> – forest tracks and mountain lanes up to the alpine pastures; bikes and e-bikes can be rented in the valley.</li>', '<li><strong>Radfahren und E-Biken</strong> – Forstwege und Bergsträßchen hinauf zu den Almen; Räder und E-Bikes gibt es im Tal zu leihen.</li>'), ('<li><strong>Drachental in Oberau</strong> – familiepark met de alpine coaster Drachenflitzer en veel te ontdekken voor kinderen.</li>', '<li><strong>Drachental in Oberau</strong> – family park with the Drachenflitzer alpine coaster and plenty for children to discover.</li>', '<li><strong>Drachental in Oberau</strong> – Familienpark mit der Alpine-Coaster „Drachenflitzer“ und viel zu entdecken für Kinder.</li>'), ('<li><strong>Zwemmen</strong> – in het verwarmde openluchtbad tussen Niederau en Oberau, met glijbaan.</li>', '<li><strong>Swimming</strong> – in the heated outdoor pool between Niederau and Oberau, complete with water slide.</li>', '<li><strong>Baden</strong> – im beheizten Freibad zwischen Niederau und Oberau, mit Rutsche.</li>'), ('<li><strong>Bergbauernmuseum z’Bach</strong> – in Oberau: zo leefde en werkte men vroeger op een bergboerderij.</li>', '<li><strong>Bergbauernmuseum z’Bach</strong> – in Oberau: how people used to live and work on a mountain farm.</li>', '<li><strong>Bergbauernmuseum z’Bach</strong> – in Oberau: so lebte und arbeitete man früher auf einem Bergbauernhof.</li>'), ('<li><strong>Paardrijden, tennis en golf</strong> – een manege in Niederau, tennisbanen in Oberau en golfbanen in Westendorf en Kitzbühel op 20 tot 30 minuten rijden.</li>', '<li><strong>Riding, tennis and golf</strong> – riding stables in Niederau, tennis courts in Oberau and golf courses in Westendorf and Kitzbühel 20 to 30 minutes’ drive away.</li>', '<li><strong>Reiten, Tennis und Golf</strong> – ein Reitstall in Niederau, Tennisplätze in Oberau und Golfplätze in Westendorf und Kitzbühel, 20 bis 30 Autominuten entfernt.</li>'), ('<li><strong>Krautinger proeven</strong> – bij een van de boeren die het eeuwenoude stookrecht nog gebruiken.</li>', '<li><strong>Tasting Krautinger</strong> – at one of the farms that still use the centuries-old distilling right.</li>', '<li><strong>Krautinger verkosten</strong> – bei einem der Bauern, die das jahrhundertealte Brennrecht noch nutzen.</li>'), ('<span class="chip">± 30 min</span><br>Het kleinste stadje van Oostenrijk: middeleeuwse straatjes en glasblazerijen waar je kunt meekijken.</li>', '<span class="chip">± 30 min</span><br>Austria’s smallest town: medieval lanes and glassblowers you can watch at work.</li>', '<span class="chip">± 30 Min.</span><br>Österreichs kleinste Stadt: mittelalterliche Gassen und Glasbläser, denen man zusehen kann.</li>'), ('<span class="chip">± 30 min</span><br>Vesting hoog boven de Inn. Elke middag om twaalf uur speelt het Heldenorgel, een van de grootste openluchtorgels ter wereld.</li>', '<span class="chip">± 30 min</span><br>Fortress high above the Inn. Every day at noon the Heldenorgel plays, one of the largest open-air organs in the world.</li>', '<span class="chip">± 30 Min.</span><br>Festung hoch über dem Inn. Täglich um zwölf Uhr erklingt die Heldenorgel, eine der größten Freiorgeln der Welt.</li>'), ('<span class="chip">± 30 min</span><br>Panoramaberg boven Hopfgarten met uitzicht op de Wilder Kaiser en, bij helder weer, de Hohe Tauern.</li>', '<span class="chip">± 30 min</span><br>Panoramic mountain above Hopfgarten with views of the Wilder Kaiser and, on clear days, the Hohe Tauern.</li>', '<span class="chip">± 30 Min.</span><br>Aussichtsberg über Hopfgarten mit Blick auf den Wilden Kaiser und bei klarer Sicht die Hohen Tauern.</li>'), ('<span class="chip">± 30 min</span><br>Openluchtmuseum met oude boerderijen die van overal in Tirol hierheen zijn verplaatst.</li>', '<span class="chip">± 30 min</span><br>Open-air museum of old farmhouses moved here from all over Tyrol.</li>', '<span class="chip">± 30 Min.</span><br>Freilichtmuseum mit alten Bauernhöfen, die aus ganz Tirol hierher versetzt wurden.</li>'), ('<span class="chip">± 40 min</span><br>Bergdorp met houten huizen en bloemrijke balkons, vaak genoemd als mooiste dorp van Oostenrijk. In de winter bereik je het ook via Ski Juwel.</li>', '<span class="chip">± 40 min</span><br>Mountain village of wooden houses and flower-filled balconies, often named the most beautiful village in Austria. In winter you can also ski there via Ski Juwel.</li>', '<span class="chip">± 40 Min.</span><br>Bergdorf mit Holzhäusern und Blumenbalkonen, oft als schönstes Dorf Österreichs bezeichnet. Im Winter auch über das Ski Juwel erreichbar.</li>'), ('<span class="chip">± 40 min</span><br>Op vaste dagen rijdt de historische stoomtrein van de Zillertalbahn vanaf Jenbach het dal in.</li>', '<span class="chip">± 40 min</span><br>On set days the historic steam train of the Zillertalbahn runs from Jenbach up the valley.</li>', '<span class="chip">± 40 Min.</span><br>An bestimmten Tagen fährt der historische Dampfzug der Zillertalbahn von Jenbach ins Tal.</li>'), ('<span class="chip">± 45 min</span><br>Kunst en kristal in een sprookjesachtige omgeving, met een grote speeltoren voor kinderen. Ook een goed plan bij regen.</li>', '<span class="chip">± 45 min</span><br>Art and crystal in a fairy-tale setting, with a big play tower for children. A good plan on a rainy day too.</li>', '<span class="chip">± 45 Min.</span><br>Kunst und Kristall in märchenhafter Umgebung, mit großem Spielturm für Kinder. Auch bei Regen eine gute Idee.</li>'), ('<span class="chip">± 45 min</span><br>Sfeervolle skistad, wereldberoemd door de Hahnenkamm-race op de Streif.</li>', '<span class="chip">± 45 min</span><br>Charming ski town, world-famous for the Hahnenkamm race on the Streif.</li>', '<span class="chip">± 45 Min.</span><br>Charmante Skistadt, weltbekannt durch das Hahnenkammrennen auf der Streif.</li>'), ('<span class="chip">± 50 min</span><br>Het grootste meer van Tirol, met rondvaartboten en wandelpaden langs de oever.</li>', '<span class="chip">± 50 min</span><br>Tyrol’s largest lake, with sightseeing boats and lakeside footpaths.</li>', '<span class="chip">± 50 Min.</span><br>Der größte See Tirols, mit Ausflugsschiffen und Uferwegen.</li>'), ('<span class="chip">± 1 uur</span><br>Oude binnenstad met het Goldenes Dachl, de Nordkettenbahn die vanuit het centrum de bergen in gaat, en de Alpenzoo.</li>', '<span class="chip">± 1 hour</span><br>Old town with the Goldenes Dachl, the Nordkettenbahn climbing straight from the centre into the mountains, and the Alpenzoo.</li>', '<span class="chip">± 1 Std.</span><br>Altstadt mit dem Goldenen Dachl, die Nordkettenbahn direkt aus dem Zentrum in die Berge und der Alpenzoo.</li>'), ('<strong>Hohe Salve en Brixental</strong>', '<strong>Hohe Salve and Brixental</strong>', '<strong>Hohe Salve und Brixental</strong>'), ('<strong>Museum Tiroler Bauernhöfe, Kramsach</strong>', '<strong>Museum Tiroler Bauernhöfe, Kramsach</strong>', '<strong>Museum Tiroler Bauernhöfe, Kramsach</strong>'), ('Of je nu komt om te skiën, te wandelen of gewoon om bij te komen: in en rond Niederau is het hele jaar genoeg te beleven. Hieronder vind je wat er in het dal te doen is en welke uitstapjes binnen een uur rijden de moeite waard zijn.', 'Whether you come to ski, to hike or simply to unwind, there is plenty to do in and around Niederau all year round. Below you will find what the valley itself has to offer and which day trips within an hour’s drive are worth it.', 'Ob zum Skifahren, Wandern oder einfach zum Abschalten: In und um Niederau gibt es das ganze Jahr viel zu erleben. Hier steht, was das Tal selbst bietet und welche Ausflüge innerhalb einer Autostunde sich lohnen.'), ('Reistijden zijn indicaties met de auto vanuit Niederau. Openingstijden en dienstregelingen wisselen per seizoen; kijk vooraf op de website van de aanbieder.', 'Travel times are approximate, by car from Niederau. Opening hours and timetables change with the seasons; check the provider’s website before you go.', 'Fahrzeiten sind Richtwerte mit dem Auto ab Niederau. Öffnungszeiten und Fahrpläne wechseln je nach Saison; bitte vorab auf der Website des Anbieters nachsehen.'), ('<strong>Slecht weer?</strong> Denk aan het Bergbauernmuseum in Oberau, de Swarovski Kristallwelten, de musea en de Alpenzoo in Innsbruck of een middag wellness.', '<strong>Bad weather?</strong> Try the Bergbauernmuseum in Oberau, the Swarovski Kristallwelten, the museums and Alpenzoo in Innsbruck, or an afternoon of wellness.', '<strong>Schlechtes Wetter?</strong> Dann bieten sich das Bergbauernmuseum in Oberau, die Swarovski Kristallwelten, die Museen und der Alpenzoo in Innsbruck oder ein Wellness-Nachmittag an.'), ('<p class="eyebrow">Activiteiten</p>', '<p class="eyebrow">Activities</p>', '<p class="eyebrow">Aktivitäten</p>'), ('Wat te doen in en rond Niederau</h2>', 'Things to do in and around Niederau</h2>', 'Was man in und um Niederau unternehmen kann</h2>'), ('<h3>In het dal – winter</h3>', '<h3>In the valley – winter</h3>', '<h3>Im Tal – Winter</h3>'), ('<h3>In het dal – zomer</h3>', '<h3>In the valley – summer</h3>', '<h3>Im Tal – Sommer</h3>'), ('<h3>Uitstapjes in de buurt</h3>', '<h3>Day trips nearby</h3>', '<h3>Ausflüge in der Umgebung</h3>')]
T["en"] += [(a, b) for a, b, c in ACT] + [('<a href="#activities">Activiteiten</a>', '<a href="#activities">Activities</a>')]
T["de"] += [(a, c) for a, b, c in ACT] + [('<a href="#aktivitaeten">Activiteiten</a>', '<a href="#aktivitaeten">Aktivitäten</a>')]

ok = True
for lang in ("en", "de"):
    html = src
    for old, new in structural(lang) + T[lang]:
        if old not in html:
            if old in OBSOLETE:
                continue
            print(f"[{lang}] NIET GEVONDEN: {old[:90]}")
            ok = False
            continue
        html = html.replace(old, new)
    out = ROOT / lang / "index.html"
    out.parent.mkdir(exist_ok=True)
    out.write_text(html, encoding="utf-8")
sys.exit(0 if ok else 1)
