#!/usr/bin/env python3
"""Bouwt en/index.html en de/index.html uit de Nederlandse index.html.
Elke NL-tekst moet exact gevonden worden; anders stopt het script."""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
src = (ROOT / "index.html").read_text(encoding="utf-8")
# SEO/GEO-blok wordt per taal opnieuw gemaakt door tools/seo.py
src = re.sub(r"<!-- SEO:START.*?<!-- SEO:END -->\n?", "", src, flags=re.S)
src = re.sub(r'<script type="application/ld\+json">.*?</script>\n?', "", src, flags=re.S)

# Structurele vervangingen (paden, ankers, taalknoppen) per taal
def structural(lang):
    ids = {
        "en": {"over": "about", "seizoenen": "seasons", "wildschonau": "wildschoenau",
               "50-jaar": "50-years", "bereikbaarheid": "getting-there", "praktisch": "practical", "verblijf": "stay"},
        "de": {"over": "dorf", "seizoenen": "jahreszeiten", "wildschonau": "wildschoenau",
               "50-jaar": "50-jahre", "bereikbaarheid": "anreise", "praktisch": "praktisch", "verblijf": "unterkunft"},
    }[lang]
    pairs = []
    for nl, new in ids.items():
        pairs += [(f'id="{nl}"', f'id="{new}"'), (f'href="#{nl}"', f'href="#{new}"')]
    pairs += [
        ('href="assets/', 'href="../assets/'),
        ('src="assets/', 'src="../assets/'),
        ('<html lang="nl">', f'<html lang="{lang}">'),
        ('<link rel="canonical" href="https://niederau.nl/">', f'<link rel="canonical" href="https://niederau.nl/{lang}/">'),
        ('<meta property="og:url" content="https://niederau.nl/">', f'<meta property="og:url" content="https://niederau.nl/{lang}/">'),
        ('"url": "https://niederau.nl/",', f'"url": "https://niederau.nl/{lang}/",'),
        ('"inLanguage": "nl",', f'"inLanguage": "{lang}",'),
        ('<meta property="og:locale" content="nl_NL">', '<meta property="og:locale" content="%s">' % ("en_GB" if lang == "en" else "de_DE")),
        ('<a href="./" hreflang="nl" lang="nl" aria-current="true">NL</a>', '<a href="../" hreflang="nl" lang="nl">NL</a>'),
        ('<a href="en/" hreflang="en" lang="en">EN</a>',
         '<a href="./" hreflang="en" lang="en" aria-current="true">EN</a>' if lang == "en" else '<a href="../en/" hreflang="en" lang="en">EN</a>'),
        ('<a href="de/" hreflang="de" lang="de">DE</a>',
         '<a href="./" hreflang="de" lang="de" aria-current="true">DE</a>' if lang == "de" else '<a href="../de/" hreflang="de" lang="de">DE</a>'),
    ]
    return pairs

T = {}
T["en"] = [
    ("<title>Niederau in de Wildschönau (Tirol) – dorp, skiën, wandelen & tips | Niederau.nl</title>",
     "<title>Niederau in the Wildschönau (Tyrol) – village, skiing, hiking & tips | Niederau.nl</title>"),
    ('content="Alles over Niederau, het zonnige bergdorp in de Wildschönau in Tirol (Oostenrijk): skiën, wandelen, de vier dorpen, Krautinger, bereikbaarheid en praktische tips – van iemand die er al 50 jaar komt."',
     'content="Everything about Niederau, the sunny mountain village in the Wildschönau valley in Tyrol (Austria): skiing, hiking, the four villages, Krautinger, getting there and practical tips – from someone who has been visiting for 50 years."'),
    ('content="Niederau – het hart van de Wildschönau"', 'content="Niederau – the heart of the Wildschönau"'),
    ('content="Bergdorp op 828 meter in Tirol. Skiën, wandelen en genieten – met tips van een vaste gast sinds 50 jaar."',
     'content="Mountain village at 828 metres in Tyrol. Skiing, hiking and enjoying life – with tips from a regular guest of 50 years."'),
    ('"description": "Bergdorp in de Wildschönau, Tirol, Oostenrijk.",', '"description": "Mountain village in the Wildschönau valley, Tyrol, Austria.",'),
    ('"name": "Wildschönau, Tirol, Oostenrijk"', '"name": "Wildschönau, Tyrol, Austria"'),
    ('"touristType": ["Wintersport", "Wandelen", "Gezinnen"]', '"touristType": ["Winter sports", "Hiking", "Families"]'),
    ('<a class="skip" href="#main">Naar de inhoud</a>', '<a class="skip" href="#main">Skip to content</a>'),
    ('aria-label="Niederau.nl – naar boven"', 'aria-label="Niederau.nl – back to top"'),
    ("<small>Wildschönau · Tirol</small>", "<small>Wildschönau · Tyrol</small>"),
    ('aria-label="Hoofdmenu"', 'aria-label="Main menu"'),
    ('<a href="#about">Het dorp</a>', '<a href="#about">The village</a>'),
    ('<a href="#seasons">Zomer &amp; winter</a>', '<a href="#seasons">Summer &amp; winter</a>'),
    ('<a href="#50-years">50 jaar</a>', '<a href="#50-years">50 years</a>'),
    ('<a href="#getting-there">Route</a>', '<a href="#getting-there">Getting there</a>'),
    ('<a href="#practical">Praktisch</a>', '<a href="#practical">Practical</a>'),
    ('aria-label="Taal"', 'aria-label="Language"'),
    ('<p class="eyebrow">Tirol · Oostenrijk</p>', '<p class="eyebrow">Tyrol · Austria</p>'),
    ("Het zonnige bergdorp aan het begin van de Wildschönau. Een plek om te skiën, te wandelen en elk jaar weer thuis te komen.",
     "The sunny mountain village at the entrance to the Wildschönau valley. A place to ski, to hike and to come home to, year after year."),
    ("<li>828 m hoogte</li>", "<li>828 m altitude</li>"),
    ("<li>± 15 min. van Wörgl</li>", "<li>± 15 min from Wörgl</li>"),
    ("Ontdek zomer &amp; winter</a>", "Discover summer &amp; winter</a>"),
    ("Hoe kom je er?</a>", "How to get there</a>"),
    ('<p class="eyebrow">Het dorp</p>', '<p class="eyebrow">The village</p>'),
    ("Welkom in Niederau</h2>", "Welcome to Niederau</h2>"),
    ("<p>Niederau is het eerste dorp dat je bereikt als je vanuit het Inndal bij Wörgl de bergweg omhoog rijdt de Wildschönau in. Het ligt op zo’n 828 meter hoogte in een breed, groen hoogdal, omringd door bergweiden, bossen en toppen in de Kitzbüheler Alpen.</p>",
     "<p>Niederau is the first village you reach when you drive up the mountain road from Wörgl in the Inn valley into the Wildschönau. It lies at about 828 metres in a wide, green high valley, surrounded by alpine meadows, forests and the peaks of the Kitzbühel Alps.</p>"),
    ("<p>Samen met Oberau, Auffach en Thierbach vormt Niederau de gemeente <strong>Wildschönau</strong> in het district Kufstein. Het dorp is van oudsher geliefd bij Nederlandse en Britse gasten: compact, gemoedelijk, met skischolen, pensions en hotels op loopafstand van de lift.</p>",
     "<p>Together with Oberau, Auffach and Thierbach, Niederau forms the municipality of <strong>Wildschönau</strong> in the Kufstein district. The village has long been a favourite with Dutch and British guests: compact and friendly, with ski schools, guesthouses and hotels within walking distance of the lift.</p>"),
    ("<p>Wie hier eenmaal geweest is, komt vaak terug. Dat geldt in ieder geval voor de maker van deze site – al vijftig jaar lang.</p>",
     "<p>Once you have been here, you tend to come back. That is certainly true for the maker of this site – for fifty years now.</p>"),
    ('aria-label="Niederau in cijfers"', 'aria-label="Niederau in numbers"'),
    ("<span>hoogte van het dorp</span>", "<span>altitude of the village</span>"),
    ("<strong>± 1.500 m</strong><span>Markbachjoch, bereikbaar met de gondel</span>", "<strong>± 1,500 m</strong><span>Markbachjoch, reached by gondola</span>"),
    ("<strong>4 dorpen</strong><span>samen de Wildschönau</span>", "<strong>4 villages</strong><span>together the Wildschönau</span>"),
    ("<span>pistes in Ski Juwel Alpbachtal Wildschönau</span>", "<span>of slopes in Ski Juwel Alpbachtal Wildschönau</span>"),
    ('<p class="eyebrow">Zomer &amp; winter</p>', '<p class="eyebrow">Summer &amp; winter</p>'),
    ("Twee seizoenen, één dorp</h2>", "Two seasons, one village</h2>"),
    ("<p>In de winter een overzichtelijk skidorp met een directe aansluiting op een groot skigebied, in de zomer een rustige uitvalsbasis voor wandelaars, fietsers en gezinnen.</p>",
     "<p>In winter a manageable ski village with direct access to a large ski area; in summer a peaceful base for hikers, cyclists and families.</p>"),
    ('aria-label="Kies seizoen"', 'aria-label="Choose season"'),
    ("☀ Zomer</button>", "☀ Summer</button>"),
    ("</span>Skiën vanuit het dorp</h3>", "</span>Skiing from the village</h3>"),
    ("<p>De Markbachjochbahn brengt je vanuit Niederau omhoog naar het Markbachjoch. Brede, zonnige pistes, ideaal voor beginners en gezinnen, met afdalingen terug tot in het dorp.</p>",
     "<p>The Markbachjochbahn gondola takes you from Niederau up to the Markbachjoch. Wide, sunny slopes, ideal for beginners and families, with runs all the way back down to the village.</p>"),
    ("<p>Met de skipas van Ski Juwel Alpbachtal Wildschönau ski je ook op de Schatzberg in Auffach en via de verbinding door naar het Alpbachtal. De skibus rijdt tussen de dorpen.</p>",
     "<p>With the Ski Juwel Alpbachtal Wildschönau lift pass you can also ski the Schatzberg in Auffach and continue over the link into the Alpbach valley. The ski bus runs between the villages.</p>"),
    ("</span>Skischool &amp; kinderen</h3>", "</span>Ski school &amp; children</h3>"),
    ("<p>Niederau heeft van oudsher sterke skischolen met lessen in het Nederlands, Engels en Duits, en oefenweides vlak bij het dorp. Een fijne plek om te leren skiën.</p>",
     "<p>Niederau has long had strong ski schools with lessons in Dutch, English and German, and nursery slopes close to the village. A great place to learn to ski.</p>"),
    ("</span>Langlaufen &amp; winterwandelen</h3>", "</span>Cross-country &amp; winter walks</h3>"),
    ("<p>Loipes door het dal en geruimde winterwandelpaden langs boerderijen en kapelletjes. Ook sneeuwschoenwandelen en rodelen zijn populair: het dal telt drie rodelbanen, die van het Lahnerköpfl ligt in Niederau zelf.</p>",
     "<p>Cross-country trails through the valley and cleared winter footpaths past farms and little chapels. Snowshoeing and tobogganing are popular too: the valley has three toboggan runs, and the Lahnerköpfl run is in Niederau itself.</p>"),
    ("<p>Gezellig zonder overdreven te zijn: na een dag op de latten schuif je aan in een berghut of in het dorp voor Glühwein, Kaiserschmarrn of een Tiroler Gröstl.</p>",
     "<p>Cosy without being over the top: after a day on the slopes, settle into a mountain hut or a village inn for Glühwein, Kaiserschmarrn or a Tyrolean Gröstl.</p>"),
    ("</span>Zonnig dorp</h3>", "</span>A sunny village</h3>"),
    ("<p>Niederau ligt open in het dal en krijgt veel zon – heerlijk op een terras in maart, wanneer de dagen langer worden en de sneeuw nog goed is.</p>",
     "<p>Niederau sits open in the valley and gets plenty of sun – wonderful on a terrace in March, when the days grow longer and the snow is still good.</p>"),
    ("</span>Wandelen</h3>", "</span>Hiking</h3>"),
    ("<p>Honderden kilometers gemarkeerde wandelpaden: van rustige dalwandelingen tot tochten over de bergkammen rond het dal. Met de gondel ben je in een paar minuten op hoogte.</p>",
     "<p>Hundreds of kilometres of waymarked trails: from gentle valley walks to hikes along the ridges around the valley. The gondola gets you up high in a few minutes.</p>"),
    ("<p>Een van de mooiste kloofwandelingen van Tirol: vanuit de Wildschönau langs de woeste Wildschönauer Ache naar beneden, naar Kundl in het Inndal.</p>",
     "<p>One of the finest gorge walks in Tyrol: from the Wildschönau down along the wild Wildschönauer Ache to Kundl in the Inn valley.</p>"),
    ("</span>(E-)mountainbiken</h3>", "</span>(E-)mountain biking</h3>"),
    ("<p>Bosweggen en bergweggetjes naar de almen; met een e-bike zijn ook de hoger gelegen hutten goed bereikbaar.</p>",
     "<p>Forest tracks and mountain lanes up to the alpine pastures; with an e-bike even the higher huts are within easy reach.</p>"),
    ("</span>Almen &amp; berghutten</h3>", "</span>Alpine pastures &amp; huts</h3>"),
    ("<p>In de zomer zijn veel almen open (“bewirtschaftet”): kaas, karnemelk, speck en Kaspressknödel met uitzicht op de Hohe Tauern en het Kaisergebergte.</p>",
     "<p>In summer many alpine huts are open: cheese, buttermilk, speck and Kaspressknödel with views of the Hohe Tauern and the Kaiser mountains.</p>"),
    ("</span>Met kinderen</h3>", "</span>With children</h3>"),
    ("<p>Speeltuinen, beekjes om te dammen, boerderijdieren en korte wandelingen met een hut als beloning. De Wildschönau is ingericht op gezinnen. Aan de rand van Niederau ligt een openluchtzwembad met drie bassins en een grote glijbaan.</p>",
     "<p>Playgrounds, streams to dam, farm animals and short walks with a hut as the reward. The Wildschönau is made for families. On the edge of Niederau there is an open-air pool with three basins and a big water slide.</p>"),
    ("</span>Traditie</h3>", "</span>Tradition</h3>"),
    ("<p>Blaasmuziek op het dorpsplein, kerkelijke feestdagen en de Almabtrieb in het najaar, wanneer het vee versierd terugkeert uit de bergen.</p>",
     "<p>Brass bands on the village square, church holidays and the Almabtrieb in autumn, when the decorated cattle return from the mountains.</p>"),
    ('<p class="eyebrow">De Wildschönau</p>', '<p class="eyebrow">The Wildschönau</p>'),
    ("Eén dal, vier dorpen</h2>", "One valley, four villages</h2>"),
    ("<p>De Wildschönau is een zijdal van het Inndal, hoog boven Wörgl. Elk dorp heeft zijn eigen karakter.</p>",
     "<p>The Wildschönau is a side valley of the Inn valley, high above Wörgl. Each village has its own character.</p>"),
    ("<p>Het eerste en meest toeristische dorp, met de gondel naar het Markbachjoch en het grootste aanbod aan accommodatie.</p>",
     "<p>The first and most visited village, with the gondola to the Markbachjoch and the widest choice of accommodation.</p>"),
    ("<p>Het bestuurlijke hart van het dal, met de grote parochiekerk en een brede, zonnige vlakte.</p>",
     "<p>The administrative heart of the valley, with the large parish church and a wide, sunny plateau.</p>"),
    ("<p>Achter in het dal, aan de voet van de Schatzberg en de verbinding met het Alpbachtal.</p>",
     "<p>At the far end of the valley, at the foot of the Schatzberg and the link to the Alpbach valley.</p>"),
    ("<span class=\"alt-badge\">± 1.150 m</span>", "<span class=\"alt-badge\">± 1,150 m</span>"),
    ("<p>Het kleinste en hoogst gelegen dorp, rustig en met weids uitzicht over het Inndal.</p>",
     "<p>The smallest and highest village, quiet and with sweeping views over the Inn valley.</p>"),
    ("<h3>Krautinger – de schnaps van het dal</h3>", "<h3>Krautinger – the valley’s own schnapps</h3>"),
    ("<p>De Wildschönau staat bekend om <em>Krautinger</em>, een stevige brandewijn gestookt van witte knollen (stoppelknollen). Volgens de overlevering kregen de boeren van het dal het recht om hem te stoken al in de tijd van keizerin Maria Theresia. Alleen een beperkt aantal boerderijen mag hem nog maken – proeven doe je op de boerderij zelf.</p>",
     "<p>The Wildschönau is known for <em>Krautinger</em>, a strong spirit distilled from white turnips. According to tradition, the valley’s farmers were granted the right to distil it as far back as Empress Maria Theresa. Only a limited number of farms may still make it – you taste it at the farm itself.</p>"),
    ("<h3>Tiroolse keuken</h3>", "<h3>Tyrolean cooking</h3>"),
    ("– gescheurde pannenkoek met poedersuiker en appelmoes</li>", "– shredded pancake with icing sugar and apple sauce</li>"),
    ("– kaasknoedels, in soep of met salade</li>", "– cheese dumplings, in soup or with salad</li>"),
    ("– gebakken aardappel, spek en ui met een ei</li>", "– fried potatoes, bacon and onion topped with an egg</li>"),
    ("<li><strong>Speckknödel</strong> en verse <strong>almkaas</strong></li>", "<li><strong>Speckknödel</strong> and fresh <strong>alpine cheese</strong></li>"),
    (">Persoonlijk</p>", ">Personal</p>"),
    ("Vijftig jaar Niederau</h2>", "Fifty years of Niederau</h2>"),
    ("<p>Deze site is gemaakt door iemand die al een halve eeuw naar Niederau komt. Wat begon als een vakantie, werd een vaste plek in het jaar. In die tijd zag ik liften komen en gaan, pensions verbouwd worden en kinderen van skileraren zelf skileraar worden. Maar de stilte op een winterochtend, de geur van hooi in de zomer en het uitzicht vanaf het Markbachjoch zijn nooit veranderd.</p>",
     "<p>This site was made by someone who has been coming to Niederau for half a century. What started as a holiday became a fixed point in the year. In that time I have seen lifts come and go, guesthouses rebuilt and ski instructors’ children become ski instructors themselves. But the silence of a winter morning, the scent of hay in summer and the view from the Markbachjoch have never changed.</p>"),
    ("<p>Op Niederau.nl deel ik wat ik in al die jaren heb geleerd: waar je heen moet, wanneer het er het mooist is en waarom je er steeds weer naar terugverlangt.</p>",
     "<p>On Niederau.nl I share what I have learned over all those years: where to go, when it is at its most beautiful and why you keep longing to return.</p>"),
    ("<!-- TIP: voeg hier eigen foto's toe (oud en nieuw), bijv.", "<!-- TIP: add your own photos here (old and new), e.g."),
    ("“Je gaat niet naar Niederau. Je komt er terug.”", "“You don’t go to Niederau. You come back to it.”"),
    ('<p class="eyebrow">Bereikbaarheid</p>', '<p class="eyebrow">Getting there</p>'),
    ("Zo kom je in Niederau</h2>", "How to reach Niederau</h2>"),
    ("<h3>Met de auto</h3>", "<h3>By car</h3>"),
    ("<li>Via Duitsland (München of Rosenheim) naar de grensovergang Kiefersfelden/Kufstein.</li>",
     "<li>Through Germany (Munich or Rosenheim) to the Kiefersfelden/Kufstein border crossing.</li>"),
    ("<li>In Oostenrijk de A12 Inntal Autobahn richting Innsbruck volgen; neem de afslag <strong>Wörgl-Ost</strong>.</li>",
     "<li>In Austria follow the A12 Inntal motorway towards Innsbruck; take the <strong>Wörgl-Ost</strong> exit.</li>"),
    ("<li>Volg in Wörgl de borden <strong>Wildschönau</strong>. De bergweg klimt in zo’n 15 minuten naar Niederau.</li>",
     "<li>In Wörgl follow the signs for <strong>Wildschönau</strong>. The mountain road climbs to Niederau in about 15 minutes.</li>"),
    ("<p class=\"note\">Let op: op de Oostenrijkse snelweg heb je een <strong>vignet</strong> nodig (digitaal of als sticker). Vanuit Midden-Nederland reken je op circa 9 à 10 uur rijden.</p>",
     "<p class=\"note\">Note: Austrian motorways require a <strong>vignette</strong> (digital or sticker). From the central Netherlands, allow around 9 to 10 hours’ driving.</p>"),
    ("<h3>Met de trein</h3>", "<h3>By train</h3>"),
    ("<p>Treinstation <strong>Wörgl Hbf</strong> ligt aan de hoofdlijn München – Innsbruck en heeft goede verbindingen, ook met nachttreinen. Vanaf Wörgl rijdt een streekbus de Wildschönau in.</p>",
     "<p><strong>Wörgl Hbf</strong> station is on the main Munich – Innsbruck line and is well connected, including by night trains. From Wörgl a regional bus runs up into the Wildschönau.</p>"),
    ("<h3>Met het vliegtuig</h3>", "<h3>By air</h3>"),
    ("<p>Dichtstbijzijnde luchthavens: <strong>Innsbruck</strong> (± 1 uur), <strong>Salzburg</strong> (± 1,5 uur) en <strong>München</strong> (± 2 uur).</p>",
     "<p>Nearest airports: <strong>Innsbruck</strong> (± 1 hour), <strong>Salzburg</strong> (± 1.5 hours) and <strong>Munich</strong> (± 2 hours).</p>"),
    ("Schematische kaart van de Wildschönau tussen Kundl en Wörgl</title>", "Schematic map of the Wildschönau between Kundl and Wörgl</title>"),
    (">Schematisch, niet op schaal</text>", ">Schematic, not to scale</text>"),
    ('<p class="eyebrow">Praktisch</p>', '<p class="eyebrow">Practical</p>'),
    ("Goed om te weten</h2>", "Good to know</h2>"),
    ("<summary>Wanneer is de beste tijd om te gaan?</summary>", "<summary>When is the best time to go?</summary>"),
    ("<p>Voor wintersport is half januari tot half maart het meest sneeuwzeker; maart is extra zonnig. In de zomer zijn juni en september rustiger dan de Duitse en Nederlandse schoolvakanties, met prima wandelweer.</p>",
     "<p>For skiing, mid-January to mid-March is the most snow-sure period; March is especially sunny. In summer, June and September are quieter than the school holidays, with fine hiking weather.</p>"),
    ("<summary>Heb ik een vignet nodig?</summary>", "<summary>Do I need a vignette?</summary>"),
    ("<p>Ja, voor de Oostenrijkse snelwegen (zoals de A12 naar Wörgl). Je koopt het online bij ASFINAG of bij tankstations vlak voor de grens. Een digitaal vignet moet je bij online aankoop enkele dagen van tevoren kopen.</p>",
     "<p>Yes, for Austrian motorways (such as the A12 to Wörgl). You can buy it online from ASFINAG or at petrol stations just before the border. If you buy a digital vignette online, do so a few days in advance.</p>"),
    ("<summary>Is Niederau geschikt voor beginners en gezinnen?</summary>", "<summary>Is Niederau suitable for beginners and families?</summary>"),
    ("<p>Zeker. De brede pistes rond het Markbachjoch, de oefenweides bij het dorp en de skischolen maken Niederau van oudsher populair bij families en beginnende skiërs.</p>",
     "<p>Definitely. The wide slopes around the Markbachjoch, the nursery slopes by the village and the ski schools have long made Niederau popular with families and beginners.</p>"),
    ("<summary>Spreekt men er Nederlands of Engels?</summary>", "<summary>Do people speak English?</summary>"),
    ("<p>De voertaal is Duits (met een stevig Tirools dialect), maar in hotels, skischolen en restaurants red je je goed met Engels, en vaak ook met Nederlands.</p>",
     "<p>The local language is German (with a strong Tyrolean dialect), but in hotels, ski schools and restaurants you will get by fine in English, and often in Dutch too.</p>"),
    ("<summary>Welke noodnummers moet ik kennen?</summary>", "<summary>Which emergency numbers should I know?</summary>"),
    ("<p>Algemeen alarmnummer <strong>112</strong>. Bergredding in Oostenrijk: <strong>140</strong>. Check vóór een toer in de winter altijd het lawinebulletin.</p>",
     "<p>General emergency number <strong>112</strong>. Mountain rescue in Austria: <strong>140</strong>. In winter, always check the avalanche bulletin before a tour.</p>"),
    ("<summary>Waar vind ik actuele informatie over liften, sneeuw en evenementen?</summary>", "<summary>Where can I find current information on lifts, snow and events?</summary>"),
    ("<p>Bij de officiële toeristische organisatie van de Wildschönau en bij Ski Juwel. Zie de links hiernaast.</p>",
     "<p>From the official Wildschönau tourist board and from Ski Juwel. See the links alongside.</p>"),
    ("<h3>Nuttige links</h3>", "<h3>Useful links</h3>"),
    ("<small>Officiële info, accommodatie, evenementen</small>", "<small>Official info, accommodation, events</small>"),
    ("<small>Liften, pistes, skipassen</small>", "<small>Lifts, slopes, lift passes</small>"),
    (">Lawinebulletin Tirol<small>", ">Tyrol avalanche bulletin<small>"),
    ("<small>Vignet en verkeersinfo</small>", "<small>Vignette and traffic info</small>"),
    ("<small>Treinen naar Wörgl</small>", "<small>Trains to Wörgl</small>"),
    ("<small>Bussen in Tirol</small>", "<small>Buses in Tyrol</small>"),
    ("Niederau.nl is een onafhankelijke, persoonlijke site en niet verbonden aan de toeristische organisatie of de liftmaatschappij. Controleer actuele tijden en prijzen altijd bij de officiële bronnen.</p>",
     "Niederau.nl is an independent, personal site and is not affiliated with the tourist board or the lift company. Always check current times and prices with the official sources.</p>"),
    ("<p>Een persoonlijke gids over Niederau in de Wildschönau, Tirol – gemaakt met liefde voor het dorp, na vijftig jaar vaste gast.</p>",
     "<p>A personal guide to Niederau in the Wildschönau, Tyrol – made with love for the village by a regular guest of fifty years.</p>"),
    ("<h4>Op deze site</h4>", "<h4>On this site</h4>"),
    ("<h4>Meer</h4>", "<h4>More</h4>"),
    ('<a href="#50-years">50 jaar Niederau</a>', '<a href="#50-years">50 years of Niederau</a>'),
    ('<a href="#practical">Praktische info</a>', '<a href="#practical">Practical info</a>'),
    ("Niederau.nl · Onafhankelijke site, niet verbonden aan officiële instanties.</p>", "Niederau.nl · Independent site, not affiliated with any official body.</p>"),
]

T["de"] = [
    ("<title>Niederau in de Wildschönau (Tirol) – dorp, skiën, wandelen & tips | Niederau.nl</title>",
     "<title>Niederau in der Wildschönau (Tirol) – Dorf, Skifahren, Wandern & Tipps | Niederau.nl</title>"),
    ('content="Alles over Niederau, het zonnige bergdorp in de Wildschönau in Tirol (Oostenrijk): skiën, wandelen, de vier dorpen, Krautinger, bereikbaarheid en praktische tips – van iemand die er al 50 jaar komt."',
     'content="Alles über Niederau, das sonnige Bergdorf in der Wildschönau in Tirol (Österreich): Skifahren, Wandern, die vier Dörfer, Krautinger, Anreise und praktische Tipps – von jemandem, der seit 50 Jahren kommt."'),
    ('content="Niederau – het hart van de Wildschönau"', 'content="Niederau – das Herz der Wildschönau"'),
    ('content="Bergdorp op 828 meter in Tirol. Skiën, wandelen en genieten – met tips van een vaste gast sinds 50 jaar."',
     'content="Bergdorf auf 828 Metern in Tirol. Skifahren, Wandern und Genießen – mit Tipps eines Stammgasts seit 50 Jahren."'),
    ('"description": "Bergdorp in de Wildschönau, Tirol, Oostenrijk.",', '"description": "Bergdorf in der Wildschönau, Tirol, Österreich.",'),
    ('"name": "Wildschönau, Tirol, Oostenrijk"', '"name": "Wildschönau, Tirol, Österreich"'),
    ('"touristType": ["Wintersport", "Wandelen", "Gezinnen"]', '"touristType": ["Wintersport", "Wandern", "Familien"]'),
    ('<a class="skip" href="#main">Naar de inhoud</a>', '<a class="skip" href="#main">Zum Inhalt</a>'),
    ('aria-label="Niederau.nl – naar boven"', 'aria-label="Niederau.nl – nach oben"'),
    ('aria-label="Hoofdmenu"', 'aria-label="Hauptmenü"'),
    ('<button class="menu-btn" aria-expanded="false" aria-controls="nav">Menu</button>', '<button class="menu-btn" aria-expanded="false" aria-controls="nav">Menü</button>'),
    ('<a href="#dorf">Het dorp</a>', '<a href="#dorf">Das Dorf</a>'),
    ('<a href="#jahreszeiten">Zomer &amp; winter</a>', '<a href="#jahreszeiten">Sommer &amp; Winter</a>'),
    ('<a href="#50-jahre">50 jaar</a>', '<a href="#50-jahre">50 Jahre</a>'),
    ('<a href="#anreise">Route</a>', '<a href="#anreise">Anreise</a>'),
    ('<a href="#praktisch">Praktisch</a>', '<a href="#praktisch">Praktisches</a>'),
    ('aria-label="Taal"', 'aria-label="Sprache"'),
    ('<p class="eyebrow">Tirol · Oostenrijk</p>', '<p class="eyebrow">Tirol · Österreich</p>'),
    ("Het zonnige bergdorp aan het begin van de Wildschönau. Een plek om te skiën, te wandelen en elk jaar weer thuis te komen.",
     "Das sonnige Bergdorf am Eingang der Wildschönau. Ein Ort zum Skifahren, zum Wandern und um jedes Jahr wieder nach Hause zu kommen."),
    ("<li>828 m hoogte</li>", "<li>828 m Seehöhe</li>"),
    ("<li>± 15 min. van Wörgl</li>", "<li>± 15 Min. von Wörgl</li>"),
    ("Ontdek zomer &amp; winter</a>", "Sommer &amp; Winter entdecken</a>"),
    ("Hoe kom je er?</a>", "Wie kommt man hin?</a>"),
    ('<p class="eyebrow">Het dorp</p>', '<p class="eyebrow">Das Dorf</p>'),
    ("Welkom in Niederau</h2>", "Willkommen in Niederau</h2>"),
    ("<p>Niederau is het eerste dorp dat je bereikt als je vanuit het Inndal bij Wörgl de bergweg omhoog rijdt de Wildschönau in. Het ligt op zo’n 828 meter hoogte in een breed, groen hoogdal, omringd door bergweiden, bossen en toppen in de Kitzbüheler Alpen.</p>",
     "<p>Niederau ist das erste Dorf, das man erreicht, wenn man von Wörgl im Inntal die Bergstraße hinauf in die Wildschönau fährt. Es liegt auf rund 828 Metern in einem weiten, grünen Hochtal, umgeben von Almwiesen, Wäldern und den Gipfeln der Kitzbüheler Alpen.</p>"),
    ("<p>Samen met Oberau, Auffach en Thierbach vormt Niederau de gemeente <strong>Wildschönau</strong> in het district Kufstein. Het dorp is van oudsher geliefd bij Nederlandse en Britse gasten: compact, gemoedelijk, met skischolen, pensions en hotels op loopafstand van de lift.</p>",
     "<p>Gemeinsam mit Oberau, Auffach und Thierbach bildet Niederau die Gemeinde <strong>Wildschönau</strong> im Bezirk Kufstein. Das Dorf ist seit jeher bei niederländischen und britischen Gästen beliebt: kompakt, gemütlich, mit Skischulen, Pensionen und Hotels in Gehweite zum Lift.</p>"),
    ("<p>Wie hier eenmaal geweest is, komt vaak terug. Dat geldt in ieder geval voor de maker van deze site – al vijftig jaar lang.</p>",
     "<p>Wer einmal hier war, kommt oft wieder. Das gilt jedenfalls für den Macher dieser Seite – seit fünfzig Jahren.</p>"),
    ('aria-label="Niederau in cijfers"', 'aria-label="Niederau in Zahlen"'),
    ("<span>hoogte van het dorp</span>", "<span>Seehöhe des Dorfes</span>"),
    ("<span>Markbachjoch, bereikbaar met de gondel</span>", "<span>Markbachjoch, mit der Gondel erreichbar</span>"),
    ("<strong>4 dorpen</strong><span>samen de Wildschönau</span>", "<strong>4 Dörfer</strong><span>bilden die Wildschönau</span>"),
    ("<span>pistes in Ski Juwel Alpbachtal Wildschönau</span>", "<span>Pisten im Ski Juwel Alpbachtal Wildschönau</span>"),
    ('<p class="eyebrow">Zomer &amp; winter</p>', '<p class="eyebrow">Sommer &amp; Winter</p>'),
    ("Twee seizoenen, één dorp</h2>", "Zwei Jahreszeiten, ein Dorf</h2>"),
    ("<p>In de winter een overzichtelijk skidorp met een directe aansluiting op een groot skigebied, in de zomer een rustige uitvalsbasis voor wandelaars, fietsers en gezinnen.</p>",
     "<p>Im Winter ein überschaubares Skidorf mit direktem Zugang zu einem großen Skigebiet, im Sommer ein ruhiger Ausgangspunkt für Wanderer, Radfahrer und Familien.</p>"),
    ('aria-label="Kies seizoen"', 'aria-label="Jahreszeit wählen"'),
    ("☀ Zomer</button>", "☀ Sommer</button>"),
    ("</span>Skiën vanuit het dorp</h3>", "</span>Skifahren direkt vom Dorf</h3>"),
    ("<p>De Markbachjochbahn brengt je vanuit Niederau omhoog naar het Markbachjoch. Brede, zonnige pistes, ideaal voor beginners en gezinnen, met afdalingen terug tot in het dorp.</p>",
     "<p>Die Markbachjochbahn bringt Sie von Niederau hinauf zum Markbachjoch. Breite, sonnige Pisten, ideal für Anfänger und Familien, mit Abfahrten bis ins Dorf.</p>"),
    ("<p>Met de skipas van Ski Juwel Alpbachtal Wildschönau ski je ook op de Schatzberg in Auffach en via de verbinding door naar het Alpbachtal. De skibus rijdt tussen de dorpen.</p>",
     "<p>Mit dem Skipass des Ski Juwel Alpbachtal Wildschönau fahren Sie auch am Schatzberg in Auffach und über die Verbindung weiter ins Alpbachtal. Der Skibus pendelt zwischen den Dörfern.</p>"),
    ("</span>Skischool &amp; kinderen</h3>", "</span>Skischule &amp; Kinder</h3>"),
    ("<p>Niederau heeft van oudsher sterke skischolen met lessen in het Nederlands, Engels en Duits, en oefenweides vlak bij het dorp. Een fijne plek om te leren skiën.</p>",
     "<p>Niederau hat seit jeher starke Skischulen mit Unterricht auf Niederländisch, Englisch und Deutsch sowie Übungswiesen direkt beim Dorf. Ein schöner Ort, um Skifahren zu lernen.</p>"),
    ("</span>Langlaufen &amp; winterwandelen</h3>", "</span>Langlaufen &amp; Winterwandern</h3>"),
    ("<p>Loipes door het dal en geruimde winterwandelpaden langs boerderijen en kapelletjes. Ook sneeuwschoenwandelen en rodelen zijn populair: het dal telt drie rodelbanen, die van het Lahnerköpfl ligt in Niederau zelf.</p>",
     "<p>Loipen durchs Tal und geräumte Winterwanderwege vorbei an Bauernhöfen und Kapellen. Auch Schneeschuhwandern und Rodeln sind beliebt: Das Tal hat drei Rodelbahnen, die am Lahnerköpfl liegt in Niederau selbst.</p>"),
    ("<p>Gezellig zonder overdreven te zijn: na een dag op de latten schuif je aan in een berghut of in het dorp voor Glühwein, Kaiserschmarrn of een Tiroler Gröstl.</p>",
     "<p>Gemütlich, ohne übertrieben zu sein: Nach einem Skitag kehrt man in einer Hütte oder im Dorf ein – auf Glühwein, Kaiserschmarrn oder ein Tiroler Gröstl.</p>"),
    ("</span>Zonnig dorp</h3>", "</span>Sonniges Dorf</h3>"),
    ("<p>Niederau ligt open in het dal en krijgt veel zon – heerlijk op een terras in maart, wanneer de dagen langer worden en de sneeuw nog goed is.</p>",
     "<p>Niederau liegt offen im Tal und bekommt viel Sonne – herrlich auf einer Terrasse im März, wenn die Tage länger werden und der Schnee noch gut ist.</p>"),
    ("</span>Wandelen</h3>", "</span>Wandern</h3>"),
    ("<p>Honderden kilometers gemarkeerde wandelpaden: van rustige dalwandelingen tot tochten over de bergkammen rond het dal. Met de gondel ben je in een paar minuten op hoogte.</p>",
     "<p>Hunderte Kilometer markierte Wanderwege: von gemütlichen Talwanderungen bis zu Touren über die Bergkämme rund ums Tal. Mit der Gondel ist man in wenigen Minuten oben.</p>"),
    ("<p>Een van de mooiste kloofwandelingen van Tirol: vanuit de Wildschönau langs de woeste Wildschönauer Ache naar beneden, naar Kundl in het Inndal.</p>",
     "<p>Eine der schönsten Klammwanderungen Tirols: von der Wildschönau entlang der wilden Wildschönauer Ache hinunter nach Kundl im Inntal.</p>"),
    ("</span>(E-)mountainbiken</h3>", "</span>(E-)Mountainbiken</h3>"),
    ("<p>Bosweggen en bergweggetjes naar de almen; met een e-bike zijn ook de hoger gelegen hutten goed bereikbaar.</p>",
     "<p>Forstwege und Bergsträßchen hinauf zu den Almen; mit dem E-Bike sind auch die höher gelegenen Hütten gut erreichbar.</p>"),
    ("</span>Almen &amp; berghutten</h3>", "</span>Almen &amp; Hütten</h3>"),
    ("<p>In de zomer zijn veel almen open (“bewirtschaftet”): kaas, karnemelk, speck en Kaspressknödel met uitzicht op de Hohe Tauern en het Kaisergebergte.</p>",
     "<p>Im Sommer sind viele Almen bewirtschaftet: Käse, Buttermilch, Speck und Kaspressknödel mit Blick auf die Hohen Tauern und das Kaisergebirge.</p>"),
    ("</span>Met kinderen</h3>", "</span>Mit Kindern</h3>"),
    ("<p>Speeltuinen, beekjes om te dammen, boerderijdieren en korte wandelingen met een hut als beloning. De Wildschönau is ingericht op gezinnen. Aan de rand van Niederau ligt een openluchtzwembad met drie bassins en een grote glijbaan.</p>",
     "<p>Spielplätze, Bäche zum Stauen, Bauernhoftiere und kurze Wanderungen mit einer Hütte als Belohnung. Die Wildschönau ist auf Familien eingestellt. Am Ortsrand von Niederau liegt ein Freibad mit drei Becken und einer großen Rutsche.</p>"),
    ("</span>Traditie</h3>", "</span>Tradition</h3>"),
    ("<p>Blaasmuziek op het dorpsplein, kerkelijke feestdagen en de Almabtrieb in het najaar, wanneer het vee versierd terugkeert uit de bergen.</p>",
     "<p>Blasmusik am Dorfplatz, kirchliche Feiertage und der Almabtrieb im Herbst, wenn das geschmückte Vieh von den Bergen zurückkehrt.</p>"),
    ('<p class="eyebrow">De Wildschönau</p>', '<p class="eyebrow">Die Wildschönau</p>'),
    ("Eén dal, vier dorpen</h2>", "Ein Tal, vier Dörfer</h2>"),
    ("<p>De Wildschönau is een zijdal van het Inndal, hoog boven Wörgl. Elk dorp heeft zijn eigen karakter.</p>",
     "<p>Die Wildschönau ist ein Seitental des Inntals, hoch über Wörgl. Jedes Dorf hat seinen eigenen Charakter.</p>"),
    ("<p>Het eerste en meest toeristische dorp, met de gondel naar het Markbachjoch en het grootste aanbod aan accommodatie.</p>",
     "<p>Das erste und touristischste Dorf, mit der Gondel zum Markbachjoch und dem größten Angebot an Unterkünften.</p>"),
    ("<p>Het bestuurlijke hart van het dal, met de grote parochiekerk en een brede, zonnige vlakte.</p>",
     "<p>Das Verwaltungszentrum des Tals, mit der großen Pfarrkirche und einem weiten, sonnigen Plateau.</p>"),
    ("<p>Achter in het dal, aan de voet van de Schatzberg en de verbinding met het Alpbachtal.</p>",
     "<p>Hinten im Tal, am Fuß des Schatzbergs und der Verbindung ins Alpbachtal.</p>"),
    ("<p>Het kleinste en hoogst gelegen dorp, rustig en met weids uitzicht over het Inndal.</p>",
     "<p>Das kleinste und höchstgelegene Dorf, ruhig und mit weitem Blick über das Inntal.</p>"),
    ("<h3>Krautinger – de schnaps van het dal</h3>", "<h3>Krautinger – der Schnaps des Tals</h3>"),
    ("<p>De Wildschönau staat bekend om <em>Krautinger</em>, een stevige brandewijn gestookt van witte knollen (stoppelknollen). Volgens de overlevering kregen de boeren van het dal het recht om hem te stoken al in de tijd van keizerin Maria Theresia. Alleen een beperkt aantal boerderijen mag hem nog maken – proeven doe je op de boerderij zelf.</p>",
     "<p>Die Wildschönau ist bekannt für den <em>Krautinger</em>, einen kräftigen Schnaps aus weißen Rüben (Stoppelrüben). Der Überlieferung nach erhielten die Bauern des Tals das Brennrecht schon zur Zeit Kaiserin Maria Theresias. Nur noch eine begrenzte Zahl von Höfen darf ihn brennen – verkostet wird direkt am Hof.</p>"),
    ("<h3>Tiroolse keuken</h3>", "<h3>Tiroler Küche</h3>"),
    ("– gescheurde pannenkoek met poedersuiker en appelmoes</li>", "– zerrissener Pfannkuchen mit Staubzucker und Apfelmus</li>"),
    ("– kaasknoedels, in soep of met salade</li>", "– Käseknödel, in der Suppe oder mit Salat</li>"),
    ("– gebakken aardappel, spek en ui met een ei</li>", "– Bratkartoffeln mit Speck und Zwiebeln, mit Spiegelei</li>"),
    ("<li><strong>Speckknödel</strong> en verse <strong>almkaas</strong></li>", "<li><strong>Speckknödel</strong> und frischer <strong>Almkäse</strong></li>"),
    (">Persoonlijk</p>", ">Persönlich</p>"),
    ("Vijftig jaar Niederau</h2>", "Fünfzig Jahre Niederau</h2>"),
    ("<p>Deze site is gemaakt door iemand die al een halve eeuw naar Niederau komt. Wat begon als een vakantie, werd een vaste plek in het jaar. In die tijd zag ik liften komen en gaan, pensions verbouwd worden en kinderen van skileraren zelf skileraar worden. Maar de stilte op een winterochtend, de geur van hooi in de zomer en het uitzicht vanaf het Markbachjoch zijn nooit veranderd.</p>",
     "<p>Diese Seite stammt von jemandem, der seit einem halben Jahrhundert nach Niederau kommt. Was als Urlaub begann, wurde zu einem festen Punkt im Jahr. In dieser Zeit habe ich Lifte kommen und gehen sehen, Pensionen wurden umgebaut, und Kinder von Skilehrern wurden selbst Skilehrer. Aber die Stille an einem Wintermorgen, der Duft von Heu im Sommer und der Blick vom Markbachjoch haben sich nie verändert.</p>"),
    ("<p>Op Niederau.nl deel ik wat ik in al die jaren heb geleerd: waar je heen moet, wanneer het er het mooist is en waarom je er steeds weer naar terugverlangt.</p>",
     "<p>Auf Niederau.nl teile ich, was ich in all den Jahren gelernt habe: wohin man gehen sollte, wann es am schönsten ist und warum man sich immer wieder zurücksehnt.</p>"),
    ("<!-- TIP: voeg hier eigen foto's toe (oud en nieuw), bijv.", "<!-- TIPP: hier eigene Fotos einfügen (alt und neu), z. B."),
    ("“Je gaat niet naar Niederau. Je komt er terug.”", "„Nach Niederau fährt man nicht. Man kommt zurück.“"),
    ('<p class="eyebrow">Bereikbaarheid</p>', '<p class="eyebrow">Anreise</p>'),
    ("Zo kom je in Niederau</h2>", "So kommen Sie nach Niederau</h2>"),
    ("<h3>Met de auto</h3>", "<h3>Mit dem Auto</h3>"),
    ("<li>Via Duitsland (München of Rosenheim) naar de grensovergang Kiefersfelden/Kufstein.</li>",
     "<li>Über München oder Rosenheim zum Grenzübergang Kiefersfelden/Kufstein.</li>"),
    ("<li>In Oostenrijk de A12 Inntal Autobahn richting Innsbruck volgen; neem de afslag <strong>Wörgl-Ost</strong>.</li>",
     "<li>In Österreich der A12 Inntalautobahn Richtung Innsbruck folgen; Ausfahrt <strong>Wörgl-Ost</strong>.</li>"),
    ("<li>Volg in Wörgl de borden <strong>Wildschönau</strong>. De bergweg klimt in zo’n 15 minuten naar Niederau.</li>",
     "<li>In Wörgl der Beschilderung <strong>Wildschönau</strong> folgen. Die Bergstraße führt in rund 15 Minuten nach Niederau.</li>"),
    ("<p class=\"note\">Let op: op de Oostenrijkse snelweg heb je een <strong>vignet</strong> nodig (digitaal of als sticker). Vanuit Midden-Nederland reken je op circa 9 à 10 uur rijden.</p>",
     "<p class=\"note\">Hinweis: Auf österreichischen Autobahnen brauchen Sie eine <strong>Vignette</strong> (digital oder als Klebevignette). Von München aus sind es rund 1,5 Stunden Fahrt.</p>"),
    ("<h3>Met de trein</h3>", "<h3>Mit der Bahn</h3>"),
    ("<p>Treinstation <strong>Wörgl Hbf</strong> ligt aan de hoofdlijn München – Innsbruck en heeft goede verbindingen, ook met nachttreinen. Vanaf Wörgl rijdt een streekbus de Wildschönau in.</p>",
     "<p>Der Bahnhof <strong>Wörgl Hbf</strong> liegt an der Hauptstrecke München – Innsbruck und ist gut angebunden, auch mit Nachtzügen. Ab Wörgl fährt ein Regionalbus in die Wildschönau.</p>"),
    ("<h3>Met het vliegtuig</h3>", "<h3>Mit dem Flugzeug</h3>"),
    ("<p>Dichtstbijzijnde luchthavens: <strong>Innsbruck</strong> (± 1 uur), <strong>Salzburg</strong> (± 1,5 uur) en <strong>München</strong> (± 2 uur).</p>",
     "<p>Nächstgelegene Flughäfen: <strong>Innsbruck</strong> (± 1 Std.), <strong>Salzburg</strong> (± 1,5 Std.) und <strong>München</strong> (± 2 Std.).</p>"),
    ("Schematische kaart van de Wildschönau tussen Kundl en Wörgl</title>", "Schematische Karte der Wildschönau zwischen Kundl und Wörgl</title>"),
    (">Schematisch, niet op schaal</text>", ">Schematisch, nicht maßstabsgetreu</text>"),
    ('<p class="eyebrow">Praktisch</p>', '<p class="eyebrow">Praktisches</p>'),
    ("Goed om te weten</h2>", "Gut zu wissen</h2>"),
    ("<summary>Wanneer is de beste tijd om te gaan?</summary>", "<summary>Wann ist die beste Reisezeit?</summary>"),
    ("<p>Voor wintersport is half januari tot half maart het meest sneeuwzeker; maart is extra zonnig. In de zomer zijn juni en september rustiger dan de Duitse en Nederlandse schoolvakanties, met prima wandelweer.</p>",
     "<p>Zum Skifahren ist Mitte Jänner bis Mitte März am schneesichersten; der März ist besonders sonnig. Im Sommer sind Juni und September ruhiger als die Schulferien – bei bestem Wanderwetter.</p>"),
    ("<summary>Heb ik een vignet nodig?</summary>", "<summary>Brauche ich eine Vignette?</summary>"),
    ("<p>Ja, voor de Oostenrijkse snelwegen (zoals de A12 naar Wörgl). Je koopt het online bij ASFINAG of bij tankstations vlak voor de grens. Een digitaal vignet moet je bij online aankoop enkele dagen van tevoren kopen.</p>",
     "<p>Ja, für österreichische Autobahnen (wie die A12 nach Wörgl). Erhältlich online bei der ASFINAG oder an Tankstellen vor der Grenze. Eine online gekaufte digitale Vignette sollten Sie einige Tage im Voraus erwerben.</p>"),
    ("<summary>Is Niederau geschikt voor beginners en gezinnen?</summary>", "<summary>Ist Niederau für Anfänger und Familien geeignet?</summary>"),
    ("<p>Zeker. De brede pistes rond het Markbachjoch, de oefenweides bij het dorp en de skischolen maken Niederau van oudsher populair bij families en beginnende skiërs.</p>",
     "<p>Auf jeden Fall. Die breiten Pisten am Markbachjoch, die Übungswiesen beim Dorf und die Skischulen machen Niederau seit jeher beliebt bei Familien und Anfängern.</p>"),
    ("<summary>Spreekt men er Nederlands of Engels?</summary>", "<summary>Spricht man dort auch Englisch oder Niederländisch?</summary>"),
    ("<p>De voertaal is Duits (met een stevig Tirools dialect), maar in hotels, skischolen en restaurants red je je goed met Engels, en vaak ook met Nederlands.</p>",
     "<p>Umgangssprache ist Deutsch (mit kräftigem Tiroler Dialekt), aber in Hotels, Skischulen und Restaurants kommt man auch mit Englisch und oft mit Niederländisch gut zurecht.</p>"),
    ("<summary>Welke noodnummers moet ik kennen?</summary>", "<summary>Welche Notrufnummern sollte ich kennen?</summary>"),
    ("<p>Algemeen alarmnummer <strong>112</strong>. Bergredding in Oostenrijk: <strong>140</strong>. Check vóór een toer in de winter altijd het lawinebulletin.</p>",
     "<p>Euronotruf <strong>112</strong>. Bergrettung in Österreich: <strong>140</strong>. Prüfen Sie im Winter vor jeder Tour den Lawinenlagebericht.</p>"),
    ("<summary>Waar vind ik actuele informatie over liften, sneeuw en evenementen?</summary>", "<summary>Wo finde ich aktuelle Infos zu Liften, Schnee und Veranstaltungen?</summary>"),
    ("<p>Bij de officiële toeristische organisatie van de Wildschönau en bij Ski Juwel. Zie de links hiernaast.</p>",
     "<p>Beim offiziellen Tourismusverband Wildschönau und beim Ski Juwel. Siehe Links nebenan.</p>"),
    ("<h3>Nuttige links</h3>", "<h3>Nützliche Links</h3>"),
    ("<small>Officiële info, accommodatie, evenementen</small>", "<small>Offizielle Infos, Unterkünfte, Veranstaltungen</small>"),
    ("<small>Liften, pistes, skipassen</small>", "<small>Lifte, Pisten, Skipässe</small>"),
    (">Lawinebulletin Tirol<small>", ">Lawinenlagebericht Tirol<small>"),
    ("<small>Vignet en verkeersinfo</small>", "<small>Vignette und Verkehrsinfo</small>"),
    ("<small>Treinen naar Wörgl</small>", "<small>Züge nach Wörgl</small>"),
    ("<small>Bussen in Tirol</small>", "<small>Busse in Tirol</small>"),
    ("Niederau.nl is een onafhankelijke, persoonlijke site en niet verbonden aan de toeristische organisatie of de liftmaatschappij. Controleer actuele tijden en prijzen altijd bij de officiële bronnen.</p>",
     "Niederau.nl ist eine unabhängige, private Seite und nicht mit dem Tourismusverband oder den Bergbahnen verbunden. Aktuelle Zeiten und Preise bitte immer bei den offiziellen Quellen prüfen.</p>"),
    ("<p>Een persoonlijke gids over Niederau in de Wildschönau, Tirol – gemaakt met liefde voor het dorp, na vijftig jaar vaste gast.</p>",
     "<p>Ein persönlicher Führer über Niederau in der Wildschönau, Tirol – mit Liebe zum Dorf gemacht, von einem Stammgast seit fünfzig Jahren.</p>"),
    ("<h4>Op deze site</h4>", "<h4>Auf dieser Seite</h4>"),
    ("<h4>Meer</h4>", "<h4>Mehr</h4>"),
    ('<a href="#50-jahre">50 jaar Niederau</a>', '<a href="#50-jahre">50 Jahre Niederau</a>'),
    ('<a href="#praktisch">Praktische info</a>', '<a href="#praktisch">Praktische Infos</a>'),
    ("Niederau.nl · Onafhankelijke site, niet verbonden aan officiële instanties.</p>", "Niederau.nl · Unabhängige Seite, nicht mit offiziellen Stellen verbunden.</p>"),
]

T["en"] += [
    ("// Seizoen: 1 okt t/m 31 mrt = winter, 1 apr t/m 30 sep = zomer", "// Season: 1 Oct – 31 Mar = winter, 1 Apr – 30 Sep = summer"),
    ('aria-label="Wissel tussen zomer- en winterversie" title="Wissel tussen zomer- en winterversie"><span data-only="winter">☀ Zomer</span>',
     'aria-label="Switch between summer and winter version" title="Switch between summer and winter version"><span data-only="winter">☀ Summer</span>'),
    ("❄ Winterseizoen: pistes vanuit het dorp, rodelen en knisperende wintermiddagen.", "❄ Winter season: slopes from the village, tobogganing and crisp winter afternoons."),
    ("☀ Zomerseizoen: almen, bergwandelingen en lange avonden op het terras.", "☀ Summer season: alpine pastures, mountain hikes and long evenings on the terrace."),
]
T["de"] += [
    ("// Seizoen: 1 okt t/m 31 mrt = winter, 1 apr t/m 30 sep = zomer", "// Saison: 1. Okt. – 31. März = Winter, 1. Apr. – 30. Sep. = Sommer"),
    ('aria-label="Wissel tussen zomer- en winterversie" title="Wissel tussen zomer- en winterversie"><span data-only="winter">☀ Zomer</span>',
     'aria-label="Zwischen Sommer- und Winterversion wechseln" title="Zwischen Sommer- und Winterversion wechseln"><span data-only="winter">☀ Sommer</span>'),
    ("❄ Winterseizoen: pistes vanuit het dorp, rodelen en knisperende wintermiddagen.", "❄ Wintersaison: Pisten direkt vom Dorf, Rodeln und klare Winternachmittage."),
    ("☀ Zomerseizoen: almen, bergwandelingen en lange avonden op het terras.", "☀ Sommersaison: Almen, Bergwanderungen und lange Abende auf der Terrasse."),
]

NL_STAY = [
    "Aanbevolen verblijf</p>",
    "Wie Niederau wil beleven, zit bij Hotel Wastlhof midden in het dorp – met de bergen achter het huis, in de winter én in de zomer.",
    "Hotel Wastlhof in de sneeuw bij avond, met verlichte gevel",
    "Hotel Wastlhof in de zomer, gezien vanuit een bloeiende bergweide",
    "Hotel Wastlhof op een zonnige winterdag met besneeuwde hellingen erachter",
    "Ligweide met rode parasols in de tuin van Hotel Wastlhof",
    "Hotel Wastlhof op een zomeravond, met verlichte balkons",
    '<span class="ad-label">Partner</span>',
    "Waarom Hotel Wastlhof?",
    "Midden in Niederau, met pistes, wandelpaden en het dorpscentrum dichtbij",
    "In de winter een sneeuwdecor vanaf de voordeur",
    "Buitenzwembad met ligweide en parasols, met de bergen als decor",
    "Typisch Tiroolse bouw met bloemrijke balkons en uitzicht op de bergen",
    "<li>Website en informatie ook in het Nederlands</li>",
    'href="https://www.hotelwastlhof.at/nl/"',
    ">Bekijk Hotel Wastlhof</a>",
    "Partner: Niederau.nl werkt samen met Hotel Wastlhof. Kijk voor prijzen, faciliteiten en beschikbaarheid op de website van het hotel.",
]
EN_STAY = [
    "Recommended stay</p>",
    "If you want to experience Niederau, Hotel Wastlhof puts you right in the heart of the village – with the mountains behind the house, in winter and in summer.",
    "Hotel Wastlhof in the snow in the evening, with its facade lit up",
    "Hotel Wastlhof in summer, seen from a flowering mountain meadow",
    "Hotel Wastlhof on a sunny winter day with snowy slopes behind",
    "Sunbathing lawn with red parasols in the garden of Hotel Wastlhof",
    "Hotel Wastlhof on a summer evening, with lit balconies",
    '<span class="ad-label">Partner</span>',
    "Why Hotel Wastlhof?",
    "Right in Niederau, with slopes, footpaths and the village centre close by",
    "In winter, a snowy scene right from the front door",
    "Outdoor pool with sun lawn and parasols, framed by the mountains",
    "Classic Tyrolean architecture with flower-filled balconies and mountain views",
    "<li>Information available in several languages, including English</li>",
    'href="https://www.hotelwastlhof.at/"',
    ">Visit Hotel Wastlhof</a>",
    "Partner: Niederau.nl works together with Hotel Wastlhof. For prices, facilities and availability, see the hotel’s website.",
]
DE_STAY = [
    "Unterkunftstipp</p>",
    "Wer Niederau erleben möchte, wohnt im Hotel Wastlhof mitten im Dorf – mit den Bergen hinterm Haus, im Winter wie im Sommer.",
    "Hotel Wastlhof im Schnee am Abend, mit beleuchteter Fassade",
    "Hotel Wastlhof im Sommer, von einer blühenden Bergwiese aus gesehen",
    "Hotel Wastlhof an einem sonnigen Wintertag mit verschneiten Hängen dahinter",
    "Liegewiese mit roten Sonnenschirmen im Garten des Hotel Wastlhof",
    "Hotel Wastlhof an einem Sommerabend, mit beleuchteten Balkonen",
    '<span class="ad-label">Partner</span>',
    "Warum Hotel Wastlhof?",
    "Mitten in Niederau, mit Pisten, Wanderwegen und Ortszentrum in der Nähe",
    "Im Winter Schneekulisse direkt vor der Haustür",
    "Freibecken mit Liegewiese und Sonnenschirmen, die Berge als Kulisse",
    "Typisch Tiroler Bauweise mit blumengeschmückten Balkonen und Bergblick",
    "<li>Informationen auch auf Niederländisch und Englisch</li>",
    'href="https://www.hotelwastlhof.at/"',
    ">Hotel Wastlhof ansehen</a>",
    "Partner: Niederau.nl arbeitet mit dem Hotel Wastlhof zusammen. Preise, Ausstattung und Verfügbarkeit finden Sie auf der Website des Hotels.",
]
T["en"] += list(zip(NL_STAY, EN_STAY)) + [
    ('<a href="#stay">Verblijf</a>', '<a href="#stay">Where to stay</a>'),
    ("Hotel Wastlhof in Niederau</h2>", "Hotel Wastlhof in Niederau</h2>"),
]
T["de"] += list(zip(NL_STAY, DE_STAY)) + [
    ('<a href="#unterkunft">Verblijf</a>', '<a href="#unterkunft">Unterkunft</a>'),
]

T["en"] += [('<a href="https://www.wildschoenau.com/"', '<a href="https://www.wildschoenau.com/en"')]

GAL_NL = ["Buitenzwembad dat ook in de winter open is: zwemmen tussen de sneeuw", "<li>Viersterrenhotel met wellness</li>",
  "Zwembad &amp; wellness</h3>",
  "Kind springt in het buitenzwembad van Hotel Wastlhof, met parasols en bergen op de achtergrond",
  "Twee gasten aan de rand van het buitenzwembad van Hotel Wastlhof",
  "Wellnessvleugel van Hotel Wastlhof met glazen serre en verlicht buitenzwembad in de sneeuw",
  "Buitenzwembad van Hotel Wastlhof in een besneeuwd landschap",
  "Badslippers en handdoeken van Hotel Wastlhof bij het zwembad"]
GAL_EN = ["Outdoor pool that stays open in winter: swimming surrounded by snow", "<li>Four-star hotel with wellness area</li>",
  "Pool &amp; wellness</h3>",
  "Child jumping into the outdoor pool of Hotel Wastlhof, with parasols and mountains behind",
  "Two guests at the edge of the outdoor pool of Hotel Wastlhof",
  "Wellness wing of Hotel Wastlhof with glass conservatory and lit outdoor pool in the snow",
  "Outdoor pool of Hotel Wastlhof in a snowy landscape",
  "Hotel Wastlhof slippers and towels by the pool"]
GAL_DE = ["Freibecken, das auch im Winter geöffnet ist: Schwimmen mitten im Schnee", "<li>Vier-Sterne-Hotel mit Wellnessbereich</li>",
  "Pool &amp; Wellness</h3>",
  "Kind springt in das Freibecken des Hotel Wastlhof, mit Sonnenschirmen und Bergen im Hintergrund",
  "Zwei Gäste am Beckenrand des Freibeckens im Hotel Wastlhof",
  "Wellnessbereich des Hotel Wastlhof mit Glaswintergarten und beleuchtetem Freibecken im Schnee",
  "Freibecken des Hotel Wastlhof in verschneiter Landschaft",
  "Badeschuhe und Handtücher des Hotel Wastlhof am Pool"]
T["en"] += list(zip(GAL_NL, GAL_EN))
T["de"] += list(zip(GAL_NL, GAL_DE))

OBSOLETE = {
    '"url": "https://niederau.nl/",', '"inLanguage": "nl",',
    '"description": "Bergdorp in de Wildschönau, Tirol, Oostenrijk.",',
    '"name": "Wildschönau, Tirol, Oostenrijk"', '"touristType": ["Wintersport", "Wandelen", "Gezinnen"]',
    '<p>De Wildschönau is een zijdal van het Inndal, hoog boven Wörgl. Elk dorp heeft zijn eigen karakter.</p>',
    "Wie Niederau wil beleven, zit bij Hotel Wastlhof midden in het dorp – met de bergen achter het huis, in de winter én in de zomer.",
    "Midden in Niederau, met pistes, wandelpaden en het dorpscentrum dichtbij",
    "In de winter een sneeuwdecor vanaf de voordeur",
    "Buitenzwembad met ligweide en parasols, met de bergen als decor",
    "Typisch Tiroolse bouw met bloemrijke balkons en uitzicht op de bergen",
    "<li>Viersterrenhotel met wellness</li>",
    "Ook sneeuwschoenwandelen en rodelen zijn populair: het dal telt drie rodelbanen, die van het Lahnerköpfl ligt in Niederau zelf.</p>",
    "De Wildschönau is ingericht op gezinnen. Aan de rand van Niederau ligt een openluchtzwembad met drie bassins en een grote glijbaan.</p>",
}
HOTEL_NL = [
    "<p>Familiebedrijf en viersterren-wellnesshotel in Niederau, in het hart van de Kitzbüheler Alpen – met het skigebied en de wandelpaden letterlijk voor de deur.</p>",
    "<li>Familiebedrijf en viersterren-wellnesshotel midden in Niederau</li>",
    "Skigebied vanaf de voordeur: na het skiën ben je meteen weer thuis",
    "Langlaufloipes beginnen bij het hotel; de rodelbaan Lahnerköpfl ligt vlak voor de deur (rodels te huur)",
    "Skiguiding: gastvrouw Margit neemt je mee naar haar favoriete pistes",
    "Relax-tuin met royaal buitenzwembad, ligweide en parasols",
    "Gasten tennissen gratis op het tenniscomplex van de Wildschönau",
    "Kamers, appartementen en suites in het hotel en de nieuwe Alpin Lodge",
    ">Bel het hotel</a>",
    "6314 Wildschönau, Oostenrijk",
]
HOTEL_EN = [
    "<p>A family-run four-star wellness hotel in Niederau, in the heart of the Kitzbühel Alps – with the ski area and hiking trails literally on the doorstep.</p>",
    "<li>Family-run four-star wellness hotel in the centre of Niederau</li>",
    "Ski from the front door: after skiing you are straight back home",
    "Cross-country trails start at the hotel; the Lahnerköpfl toboggan run is right outside (sledges for hire)",
    "Ski guiding: hostess Margit takes you to her favourite slopes",
    "Relaxation garden with a generous outdoor pool, sun lawn and parasols",
    "Guests play tennis free of charge at the Wildschönau tennis complex",
    "Rooms, apartments and suites in the hotel and the new Alpin Lodge",
    ">Call the hotel</a>",
    "6314 Wildschönau, Austria",
]
HOTEL_DE = [
    "<p>Familienbetrieb und Vier-Sterne-Wellnesshotel in Niederau, im Herzen der Kitzbüheler Alpen – mit Skigebiet und Wanderwegen direkt vor der Tür.</p>",
    "<li>Familienbetrieb und Vier-Sterne-Wellnesshotel mitten in Niederau</li>",
    "Skigebiet ab der Haustür: nach dem Skifahren gleich wieder daheim",
    "Langlaufloipen starten beim Hotel; die Rodelbahn Lahnerköpfl liegt direkt vor der Tür (Rodelverleih)",
    "Skiguiding: Gastgeberin Margit zeigt Ihnen ihre Lieblingspisten",
    "Relax-Garten mit großzügigem Freibecken, Liegewiese und Sonnenschirmen",
    "Gäste spielen gratis Tennis auf der Wildschönauer Tennisanlage",
    "Zimmer, Appartements und Suiten im Hotel und in der neuen Alpin Lodge",
    ">Hotel anrufen</a>",
    "6314 Wildschönau, Österreich",
]
T["en"] += list(zip(HOTEL_NL, HOTEL_EN))
T["de"] += list(zip(HOTEL_NL, HOTEL_DE))

T["en"] += [("<li>Paardrijden vanuit het hotel, in de zomer én in de winter</li>", "<li>Horse riding from the hotel, in summer and in winter</li>")]
T["de"] += [("<li>Paardrijden vanuit het hotel, in de zomer én in de winter</li>", "<li>Reiten direkt vom Hotel aus, im Sommer wie im Winter</li>")]

T['en'] += [('<p>Het hoogdal Wildschönau ligt in de Kitzbüheler Alpen en staat bekend als een zonnige en sneeuwzekere bestemming. Mede dankzij de vriendelijke uitstraling won het dal de eerste prijs van de ADAC – de Duitse ANWB – in de categorie “Klein &amp; Fein”.</p>\n      <p>De Wildschönau bestaat uit de vier kerkdorpen Niederau, Oberau, Auffach en Thierbach, plus het gehucht Mühltal. Het dal is bij uitstek geschikt voor ontspannen skiën midden in een prachtige bergwereld. De regio is altijd goed bereikbaar, ligt niet ver van Kufstein en biedt naast traditionele wintersport ook een veelzijdig zomeraanbod.</p>', '<p>The Wildschönau high valley lies in the Kitzbühel Alps and is known as a sunny, snow-sure destination. Thanks in part to its friendly character, the valley won first prize from the ADAC – Germany’s largest motoring club – in the “Klein &amp; Fein” (small and fine) category.</p>\n      <p>The Wildschönau is made up of four church villages – Niederau, Oberau, Auffach and Thierbach – plus the hamlet of Mühltal. The valley is ideal for relaxed skiing amid a magnificent mountain landscape. Always easy to reach and not far from Kufstein, it offers a varied summer programme as well as traditional winter sports.</p>')]
T['de'] += [('<p>Het hoogdal Wildschönau ligt in de Kitzbüheler Alpen en staat bekend als een zonnige en sneeuwzekere bestemming. Mede dankzij de vriendelijke uitstraling won het dal de eerste prijs van de ADAC – de Duitse ANWB – in de categorie “Klein &amp; Fein”.</p>\n      <p>De Wildschönau bestaat uit de vier kerkdorpen Niederau, Oberau, Auffach en Thierbach, plus het gehucht Mühltal. Het dal is bij uitstek geschikt voor ontspannen skiën midden in een prachtige bergwereld. De regio is altijd goed bereikbaar, ligt niet ver van Kufstein en biedt naast traditionele wintersport ook een veelzijdig zomeraanbod.</p>', '<p>Das Hochtal Wildschönau liegt in den Kitzbüheler Alpen und gilt als sonniges und schneesicheres Urlaubsziel. Nicht zuletzt dank seiner freundlichen Ausstrahlung erhielt das Tal den ersten Preis des ADAC in der Kategorie „Klein &amp; Fein“.</p>\n      <p>Die Wildschönau besteht aus den vier Kirchdörfern Niederau, Oberau, Auffach und Thierbach sowie dem Weiler Mühltal. Das Tal eignet sich besonders für entspanntes Skifahren inmitten einer herrlichen Bergwelt. Die stets gut erreichbare Urlaubsregion liegt nicht weit von Kufstein und bietet neben dem klassischen Wintersport auch ein vielseitiges Sommerangebot.</p>')]

EIGEN_NL = ["Eigen foto’s</h3>",
  "Uitzicht op besneeuwde pistes en liften in de Wildschönau bij winterzon (eigen foto)",
  "Oefenlift en skihut aan de voet van de piste in de Wildschönau, na verse sneeuwval (eigen foto)",
  "Snowboarder op een zonnige helling in de Wildschönau (eigen foto)"]
EIGEN_EN = ["My own photos</h3>",
  "View of snowy slopes and lifts in the Wildschönau in winter sunshine (own photo)",
  "Beginners’ lift and ski hut at the foot of the slope in the Wildschönau, after fresh snowfall (own photo)",
  "Snowboarder on a sunny slope in the Wildschönau (own photo)"]
EIGEN_DE = ["Eigene Fotos</h3>",
  "Blick auf verschneite Pisten und Lifte in der Wildschönau bei Wintersonne (eigenes Foto)",
  "Übungslift und Skihütte am Fuß der Piste in der Wildschönau nach frischem Neuschnee (eigenes Foto)",
  "Snowboarder an einem sonnigen Hang in der Wildschönau (eigenes Foto)"]
T["en"] += list(zip(EIGEN_NL, EIGEN_EN))
T["de"] += list(zip(EIGEN_NL, EIGEN_DE))

ok = True
for lang in ("en", "de"):
    html = src
    for old, new in structural(lang) + T[lang]:
        if old not in html:
            if old in OBSOLETE:
                continue
            print(f"[{lang}] NIET GEVONDEN: {old[:90]}")
            ok = False
            continue
        html = html.replace(old, new)
    out = ROOT / lang / "index.html"
    out.parent.mkdir(exist_ok=True)
    out.write_text(html, encoding="utf-8")
sys.exit(0 if ok else 1)
